! This file was generated by MFC. It is only used if the --case-optimization
! option is passed to ./mfc.sh run or test, enabling a GPU-oriented optimization
! that hard-codes certain case parameters from the input file.

#:set MFC_CASE_OPTIMIZATION = True

#:set weno_order = 5
#:set weno_polyn = 2
#:set nb         = 1
#:set num_dims   = 3
#:set nterms     = 1
#:set num_fluids = 2
