name: Docker Publisher

on:
  push:
    branches: [ "master" ]
    paths:
      - toolchain/Dockerfile

  workflow_dispatch:

jobs:
  push_to_registry:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Publish thereto
      uses: docker/build-push-action@v4
      with:
        file: toolchain/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/mfc:latest
