coverage:
  status:
    project:
      default:
        target: 80%       # Based on 83.7% baseline with -a flag
        threshold: 2%     # Allow 2% drop (81.7% minimum)
    patch:
      default:
        target: 70%       # New code should be reasonably tested
        threshold: 10%    # Some flexibility for new features
