coverage:
  strict_yaml_branch: default
  max_report_age: off
  status:
    project:
      default:
        target: 1%
        threshold: 1%
    patch:
      default:
        target: 1%
        threshold: 1%
