! AUTO-GENERATED - do not edit directly. Regenerate: ./mfc.sh generate
!
real(wp)                :: Bx0
real(wp)                :: Ca
real(wp)                :: R0ref
real(wp)                :: Re_inv
real(wp)                :: Web
logical                 :: acoustic_source
logical                 :: adap_dt
integer                 :: adap_dt_max_iters
real(wp)                :: adap_dt_tol
logical                 :: adv_n
real(wp)                :: alf_factor
real(wp)                :: alpha_bar
logical                 :: alt_soundspeed
integer                 :: avg_state
logical                 :: bf_x
logical                 :: bf_y
logical                 :: bf_z
integer                 :: bubble_model
logical                 :: bubbles_euler
logical                 :: bubbles_lagrange
character(LEN=path_len) :: case_dir
logical                 :: cfl_adap_dt
logical                 :: cfl_const_dt
real(wp)                :: cfl_target
real(wp)                :: coefficient_of_restitution
integer                 :: collision_model
real(wp)                :: collision_time
logical                 :: cont_damage
real(wp)                :: cont_damage_s
logical                 :: cyl_coord
logical                 :: down_sample
real(wp)                :: dt
integer                 :: fd_order
logical                 :: fft_wrt
logical                 :: file_per_process
real(wp)                :: g_x
real(wp)                :: g_y
real(wp)                :: g_z
logical                 :: hyper_cleaning
real(wp)                :: hyper_cleaning_speed
real(wp)                :: hyper_cleaning_tau
logical                 :: hyperelasticity
logical                 :: hypoelasticity
logical                 :: ib
real(wp)                :: ib_coefficient_of_friction
logical                 :: ib_state_wrt
real(wp)                :: ic_beta
real(wp)                :: ic_eps
logical                 :: igr
integer                 :: igr_iter_solver
integer                 :: igr_order
logical                 :: igr_pres_lim
integer                 :: int_comp
logical                 :: integral_wrt
real(wp)                :: k_x
real(wp)                :: k_y
real(wp)                :: k_z
integer                 :: low_Mach
integer                 :: m
logical                 :: mapped_weno
logical                 :: mhd
logical                 :: mixture_err
integer                 :: model_eqns
logical                 :: mp_weno
logical                 :: mpp_lim
real(wp)                :: muscl_eps
integer                 :: muscl_lim
integer                 :: muscl_order
integer                 :: n
integer                 :: n_start
integer                 :: nb
logical                 :: null_weights
integer                 :: num_bc_patches
integer                 :: num_fluids
integer                 :: num_ibs
integer                 :: num_igr_iters
integer                 :: num_igr_warm_start_iters
integer                 :: num_integrals
integer                 :: num_probes
integer                 :: num_source
integer                 :: nv_uvm_igr_temps_on_gpu
logical                 :: nv_uvm_out_of_core
logical                 :: nv_uvm_pref_gpu
integer                 :: p
real(wp)                :: p_x
real(wp)                :: p_y
real(wp)                :: p_z
real(wp)                :: palpha_eps
logical                 :: parallel_io
real(wp)                :: pi_fac
real(wp)                :: poly_sigma
logical                 :: polydisperse
logical                 :: polytropic
integer                 :: precision
real(wp)                :: pref
logical                 :: prim_vars_wrt
logical                 :: probe_wrt
real(wp)                :: ptgalpha_eps
logical                 :: qbmm
logical                 :: rdma_mpi
integer                 :: recon_type
logical                 :: relativity
logical                 :: relax
integer                 :: relax_model
real(wp)                :: rhoref
integer                 :: riemann_solver
logical                 :: run_time_info
real(wp)                :: sigma
logical                 :: surface_tension
real(wp)                :: t_save
integer                 :: t_step_old
integer                 :: t_step_print
integer                 :: t_step_save
integer                 :: t_step_start
integer                 :: t_step_stop
real(wp)                :: t_stop
real(wp)                :: tau_star
logical                 :: teno
real(wp)                :: teno_CT
integer                 :: thermal
integer                 :: time_stepper
logical                 :: viscous
real(wp)                :: w_x
real(wp)                :: w_y
real(wp)                :: w_z
integer                 :: wave_speeds
logical                 :: weno_Re_flux
logical                 :: weno_avg
real(wp)                :: weno_eps
integer                 :: weno_order
logical                 :: wenoz
real(wp)                :: wenoz_q
real(wp)                :: x_a
real(wp)                :: x_b
real(wp)                :: y_a
real(wp)                :: y_b
real(wp)                :: z_a
real(wp)                :: z_b
