! AUTO-GENERATED - do not edit directly. Regenerate: ./mfc.sh generate
!
real(wp)                :: Bx0
real(wp)                :: Ca
logical                 :: E_wrt
real(wp)                :: R0ref
real(wp)                :: Re_inv
real(wp)                :: Web
logical                 :: adv_n
logical                 :: alpha_rho_wrt
logical                 :: alpha_wrt
logical                 :: alt_soundspeed
integer                 :: avg_state
logical                 :: bubbles_euler
logical                 :: bubbles_lagrange
logical                 :: c_wrt
character(LEN=path_len) :: case_dir
logical                 :: cf_wrt
logical                 :: cfl_adap_dt
logical                 :: cfl_const_dt
real(wp)                :: cfl_target
logical                 :: chem_wrt_T
logical                 :: cons_vars_wrt
logical                 :: cont_damage
logical                 :: cyl_coord
logical                 :: down_sample
integer                 :: fd_order
logical                 :: fft_wrt
logical                 :: file_per_process
integer                 :: flux_lim
logical                 :: flux_wrt
integer                 :: format
logical                 :: gamma_wrt
logical                 :: heat_ratio_wrt
logical                 :: hyper_cleaning
logical                 :: hyperelasticity
logical                 :: hypoelasticity
logical                 :: ib
logical                 :: ib_state_wrt
logical                 :: igr
integer                 :: igr_order
logical                 :: lag_betaC_wrt
logical                 :: lag_betaT_wrt
logical                 :: lag_db_wrt
logical                 :: lag_dphidt_wrt
logical                 :: lag_header
logical                 :: lag_id_wrt
logical                 :: lag_mg_wrt
logical                 :: lag_mv_wrt
logical                 :: lag_pos_prev_wrt
logical                 :: lag_pos_wrt
logical                 :: lag_pres_wrt
logical                 :: lag_r0_wrt
logical                 :: lag_rad_wrt
logical                 :: lag_rmax_wrt
logical                 :: lag_rmin_wrt
logical                 :: lag_rvel_wrt
logical                 :: lag_txt_wrt
logical                 :: lag_vel_wrt
logical                 :: liutex_wrt
integer                 :: m
logical                 :: mhd
logical                 :: mixture_err
integer                 :: model_eqns
logical                 :: mom_wrt
logical                 :: mpp_lim
integer                 :: muscl_order
integer                 :: n
integer                 :: n_start
real(wp)                :: nb
integer                 :: num_bc_patches
integer                 :: num_fluids
integer                 :: num_ibs
logical                 :: omega_wrt
logical                 :: output_partial_domain
integer                 :: p
logical                 :: parallel_io
logical                 :: pi_inf_wrt
real(wp)                :: poly_sigma
logical                 :: polydisperse
logical                 :: polytropic
integer                 :: precision
real(wp)                :: pref
logical                 :: pres_inf_wrt
logical                 :: pres_wrt
logical                 :: prim_vars_wrt
logical                 :: qbmm
logical                 :: qm_wrt
integer                 :: recon_type
logical                 :: relativity
logical                 :: relax
integer                 :: relax_model
logical                 :: rho_wrt
real(wp)                :: rhoref
real(wp)                :: schlieren_alpha
logical                 :: schlieren_wrt
real(wp)                :: sigR
real(wp)                :: sigma
logical                 :: sim_data
logical                 :: surface_tension
real(wp)                :: t_save
integer                 :: t_step_save
integer                 :: t_step_start
integer                 :: t_step_stop
real(wp)                :: t_stop
integer                 :: thermal
logical                 :: vel_wrt
integer                 :: weno_order
