# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-US

reviews:
  profile: chill
  review_status: false
  enable_prompt_for_ai_agents: false

  auto_review:
    enabled: true                  # initial PR-open review
    auto_incremental_review: false # no re-run on every push

  path_instructions:
    - path: "**/*"
      instructions: |
        IMPORTANT: Only comment on code that is within this PR’s diff (changed lines / files).
        Do not add feedback that requires commenting outside the diff range.

    - path: "src/**/*.fpp"
      instructions: |
        Fortran source (Fypp-preprocessed). Follow the coding standards in
        docs/documentation/contributing.md and the GPU macro API in
        docs/documentation/gpuParallelization.md and the coding standards in
        docs/documentation/contributing.md.
    - path: "toolchain/**/*.py"
      instructions: |
        Python toolchain code. Follow PEP 8. Requires Python 3.10+;
        do not suggest __future__ imports or backwards-compatibility shims.

knowledge_base:
  code_guidelines:
    enabled: true
    filePatterns:
      - "docs/documentation/contributing.md"
      - "docs/documentation/gpuParallelization.md"
      - ".github/copilot-instructions.md"
