# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-us

reviews:
  profile: chill
  path_instructions:
    - path: "src/**/*.fpp"
      instructions: |
        Fortran source (Fypp-preprocessed). Follow the coding standards in
        .github/copilot-instructions.md. Pay attention to naming conventions,
        GPU compatibility (OpenACC), and error handling (s_mpi_abort, not stop).
    - path: "src/**/*.f90"
      instructions: |
        Fortran source. Follow the coding standards in
        .github/copilot-instructions.md.
    - path: "toolchain/**/*.py"
      instructions: |
        Python toolchain code. Follow PEP 8.

knowledge_base:
  code_guidelines:
    enabled: true
    filePatterns:
      - ".github/copilot-instructions.md"
      - "docs/documentation/contributing.md"
