# For compiler-specific modules, options [gcc,intel]
mycompiler="intel"

# FFTW library location
fftw_dir = /usr/local/lib

# FFTW include location
#fftw_include_dir = /usr/include
fftw_include_dir = /usr/local/include

# Silo location
silo_dir = /home/spencer/packages/silo-4.10.2

# Compiler command
compiler = mpif90
#compiler = mpiifort
