#!/bin/bash
# MFC Shell Completion Auto-installer
#
# This script handles automatic installation and updating of shell completions.
# It is sourced by mfc.sh on startup.
#
# Features:
# - Auto-detects bash vs zsh
# - Installs completions to ~/.local/share/mfc/completions/
# - Updates completions when source files change
# - Configures shell rc files on first install
# - Sources completions immediately when mfc.sh is sourced

_mfc_setup_completions() {
    local MFC_ROOT="$1"
    local COMPLETION_DIR="$HOME/.local/share/mfc/completions"
    local COMPLETION_SRC="$MFC_ROOT/toolchain/completions"
    local COMPLETION_FILE SOURCE_FILE RC_FILE RC_LINE SOURCE_CMD

    # Detect zsh: prefer current shell (ZSH_VERSION), fall back to $SHELL only if not in bash
    if [ -n "${ZSH_VERSION-}" ] || { [ -z "${BASH_VERSION-}" ] && [[ "${SHELL-}" == *"zsh" ]]; }; then
        COMPLETION_FILE="$COMPLETION_DIR/_mfc"
        SOURCE_FILE="$COMPLETION_SRC/_mfc"
        RC_FILE="$HOME/.zshrc"
        RC_LINE="fpath=(\"$COMPLETION_DIR\" \$fpath)"
        SOURCE_CMD="source $COMPLETION_DIR/_mfc"
    else
        COMPLETION_FILE="$COMPLETION_DIR/mfc.bash"
        SOURCE_FILE="$COMPLETION_SRC/mfc.bash"
        RC_FILE="$HOME/.bashrc"
        RC_LINE="[ -f \"$COMPLETION_DIR/mfc.bash\" ] && source \"$COMPLETION_DIR/mfc.bash\""
        SOURCE_CMD="source $COMPLETION_DIR/mfc.bash"
    fi

    # Check if we need to install or update
    local COMPLETIONS_CHANGED=false

    # Only proceed if source completion files exist (they're generated by ./mfc.sh generate)
    if [ ! -f "$COMPLETION_SRC/mfc.bash" ] || [ ! -f "$COMPLETION_SRC/_mfc" ]; then
        return
    fi

    if [ ! -f "$COMPLETION_FILE" ]; then
        # Fresh install
        mkdir -p "$COMPLETION_DIR"
        cp "$COMPLETION_SRC/mfc.bash" "$COMPLETION_DIR/"
        cp "$COMPLETION_SRC/_mfc" "$COMPLETION_DIR/"
        COMPLETIONS_CHANGED=true

        # Add to shell rc file on first install
        if [ -f "$RC_FILE" ] && ! grep -q "$COMPLETION_DIR" "$RC_FILE" 2>/dev/null; then
            echo "" >> "$RC_FILE"
            echo "# MFC shell completion" >> "$RC_FILE"
            echo "$RC_LINE" >> "$RC_FILE"
        fi
    elif [ "$SOURCE_FILE" -nt "$COMPLETION_FILE" ]; then
        # Update outdated completions
        cp "$COMPLETION_SRC/mfc.bash" "$COMPLETION_DIR/"
        cp "$COMPLETION_SRC/_mfc" "$COMPLETION_DIR/"
        COMPLETIONS_CHANGED=true
    fi

    # Notify user about changes
    if [ "$COMPLETIONS_CHANGED" = true ]; then
        if [[ "${BASH_SOURCE[1]}" != "${0}" ]] 2>/dev/null; then
            # Script is being sourced - activate completions now
            # shellcheck disable=SC1090
            source "$COMPLETION_FILE" 2>/dev/null && log "Tab completions activated."
        else
            # Script is being executed - can't modify parent shell
            log "Tab completions updated. Run:$MAGENTA $SOURCE_CMD$COLOR_RESET"
        fi
    fi
}

# Run setup if this script is sourced with MFC_ROOT_DIR set
if [ -n "$1" ]; then
    _mfc_setup_completions "$1"
fi
