#!/usr/bin/env python3
"""2D axisymmetric hypoelastic acoustic case (default HLLD): liquid + solid square, focused acoustic source.
   Base for HLL/HLLC/HLLD tests. x=axial, y=radial; resolution 49^2; riemann_solver=4 (HLLD); wave_speeds=1, avg_state=2, alt_soundspeed=T, mpp_lim=F.
   Tests may apply y_domain%end=0.5 for half-height."""
import json

config = {
    "run_time_info": "T",
    "x_domain%beg": 0,
    "x_domain%end": 1.,
    "y_domain%beg": 0,
    "y_domain%end": 0.5,
    "cyl_coord": "T",
    "m": 49,
    "n": 24,
    "p": 0,
    "dt": 1.0e-6,
    "t_step_start": 0,
    "t_step_stop": 1500,
    "t_step_save": 50,
    "num_patches": 2,
    "model_eqns": 2,
    "alt_soundspeed": "T",
    "num_fluids": 2,
    "mpp_lim": "F",
    "mixture_err": "F",
    "time_stepper": 1,
    "weno_order": 1,
    "weno_eps": 1.0e-20,
    "null_weights": "F",
    "mp_weno": "F",
    "riemann_solver": 4,
    "wave_speeds": 1,
    "avg_state": 2,
    "bc_x%beg": -2,
    "bc_x%end": -2,
    "bc_y%beg": -2,
    "bc_y%end": -2,
    "format": 1,
    "precision": 2,
    "prim_vars_wrt": "T",
    "rho_wrt": "T",
    "parallel_io": "T",
    "hypoelasticity": "T",
    "fd_order": 4,
    "patch_icpp(1)%geometry": 3,
    "patch_icpp(1)%x_centroid": 0.5,
    "patch_icpp(1)%y_centroid": 0.25,
    "patch_icpp(1)%length_x": 1.,
    "patch_icpp(1)%length_y": 0.5,
    "patch_icpp(1)%vel(1)": 0.0,
    "patch_icpp(1)%vel(2)": 0.0,
    "patch_icpp(1)%pres": 1e05,
    "patch_icpp(1)%tau_e(1)": 0.0,
    "patch_icpp(1)%alpha_rho(1)": 1000*(1.0 - 1e-8),
    "patch_icpp(1)%alpha(1)": 1.0 - 1e-8,
    "patch_icpp(1)%alpha_rho(2)": 1000*1e-8,
    "patch_icpp(1)%alpha(2)": 1e-8,
    "patch_icpp(2)%alter_patch(1)": "T",
    "patch_icpp(2)%geometry": 3,
    "patch_icpp(2)%x_centroid": 0.6,
    "patch_icpp(2)%y_centroid": 0.2,
    "patch_icpp(2)%length_x": 0.2,
    "patch_icpp(2)%length_y": 0.15,
    "patch_icpp(2)%vel(1)": 0.0,
    "patch_icpp(2)%vel(2)": 0.0,
    "patch_icpp(2)%pres": 1e05,
    "patch_icpp(2)%tau_e(1)": 0.0,
    "patch_icpp(2)%alpha_rho(1)": 1000*1e-8,
    "patch_icpp(2)%alpha(1)": 1e-8,
    "patch_icpp(2)%alpha_rho(2)": 1000*(1.0 - 1e-8),
    "patch_icpp(2)%alpha(2)": 1.0 - 1e-8,
    "acoustic_source": "T",
    "num_source": 1,
    "acoustic(1)%support": 6,
    "acoustic(1)%loc(1)": 0.1,
    "acoustic(1)%loc(2)": 0.0,
    "acoustic(1)%pulse": 2,
    "acoustic(1)%npulse": 1,
    "acoustic(1)%mag": 1.0,
    "acoustic(1)%foc_length": 0.8,
    "acoustic(1)%aperture": 0.4,
    "acoustic(1)%gauss_sigma_time": 4e-5,
    "acoustic(1)%delay": 2e-4,
    "fluid_pp(1)%gamma": 1.0e00 / (4.4e00 - 1.0e00),
    "fluid_pp(1)%pi_inf": 4.4e00 * 5.57e08 / (4.4e00 - 1.0e00),
    "fluid_pp(1)%G": 0.0,
    "fluid_pp(2)%gamma": 1.0e00 / (4.4e00 - 1.0e00),
    "fluid_pp(2)%pi_inf": 4.4e00 * 5.57e08 / (4.4e00 - 1.0e00),
    "fluid_pp(2)%G": 1e9,
}

print(json.dumps(config, indent=4))
