"""
Documentation Generator for MFC Parameters.

Generates markdown documentation from the parameter registry,
providing a single source of truth for parameter documentation.
"""

from typing import Dict, List, Optional
from collections import defaultdict

from ..schema import Stage, ParamType, ParamDef
from ..registry import ParamRegistry


def generate_param_docs(registry: ParamRegistry, format: str = "markdown") -> str:
    """
    Generate parameter documentation from the registry.

    Args:
        registry: The parameter registry
        format: Output format ('markdown' or 'html')

    Returns:
        Documentation as a string
    """
    if format == "markdown":
        return _generate_markdown(registry)
    elif format == "html":
        return _generate_html(registry)
    else:
        raise ValueError(f"Unknown format: {format}")


def _generate_markdown(registry: ParamRegistry) -> str:
    """Generate markdown documentation."""
    lines = [
        "# MFC Parameter Reference",
        "",
        "This documentation is auto-generated from the parameter registry.",
        "",
        f"**Total Parameters:** {registry.param_count}",
        f"**Total Constraints:** {registry.constraint_count}",
        "",
    ]

    # Group parameters by category
    by_category: Dict[str, List[ParamDef]] = defaultdict(list)
    for name, param in sorted(registry.all_params.items()):
        cat = param.category or "other"
        by_category[cat].append(param)

    # Generate table of contents
    lines.append("## Table of Contents")
    lines.append("")
    for cat in sorted(by_category.keys()):
        cat_title = cat.replace("_", " ").title()
        lines.append(f"- [{cat_title}](#{cat.replace('_', '-')})")
    lines.append("")

    # Generate sections by category
    for cat in sorted(by_category.keys()):
        params = by_category[cat]
        cat_title = cat.replace("_", " ").title()

        lines.append(f"## {cat_title}")
        lines.append("")
        lines.append(f"*{len(params)} parameters*")
        lines.append("")

        # Create table
        lines.append("| Parameter | Type | Stages | Description |")
        lines.append("|-----------|------|--------|-------------|")

        for param in sorted(params, key=lambda p: p.name):
            type_str = _type_to_str(param.param_type)
            stages_str = ", ".join(s.name for s in sorted(param.stages, key=lambda s: s.value))
            desc = param.description or "-"
            # Escape pipes in description
            desc = desc.replace("|", "\\|")
            lines.append(f"| `{param.name}` | {type_str} | {stages_str} | {desc} |")

        lines.append("")

    # Add constraints section
    lines.append("## Validation Constraints")
    lines.append("")
    lines.append(f"*{registry.constraint_count} constraints defined*")
    lines.append("")

    constraints = list(registry.all_constraints.values())
    if constraints:
        lines.append("| Constraint | Type | Parameters | Message |")
        lines.append("|------------|------|------------|---------|")

        for rule in sorted(constraints, key=lambda r: r.rule_id):
            params_str = ", ".join(f"`{p}`" for p in rule.params[:3])
            if len(rule.params) > 3:
                params_str += f" (+{len(rule.params) - 3})"
            msg = rule.message or "-"
            msg = msg.replace("|", "\\|")[:50]
            if len(rule.message or "") > 50:
                msg += "..."
            lines.append(f"| {rule.rule_id} | {rule.constraint_type.name} | {params_str} | {msg} |")

    lines.append("")
    lines.append("---")
    lines.append("*Generated by mfc.params.generators.docs_gen*")

    return "\n".join(lines)


def _generate_html(registry: ParamRegistry) -> str:
    """Generate HTML documentation."""
    # Simple HTML wrapper around markdown content
    md = _generate_markdown(registry)

    return f"""<!DOCTYPE html>
<html>
<head>
    <title>MFC Parameter Reference</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
               max-width: 1200px; margin: 0 auto; padding: 20px; }}
        table {{ border-collapse: collapse; width: 100%; }}
        th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
        th {{ background-color: #f2f2f2; }}
        code {{ background-color: #f4f4f4; padding: 2px 6px; border-radius: 3px; }}
        h2 {{ border-bottom: 1px solid #eee; padding-bottom: 10px; }}
    </style>
</head>
<body>
<pre>{md}</pre>
</body>
</html>
"""


def _type_to_str(ptype: ParamType) -> str:
    """Convert ParamType to human-readable string."""
    type_names = {
        ParamType.INT: "Integer",
        ParamType.REAL: "Real",
        ParamType.LOG: "Logical",
        ParamType.STR: "String",
        ParamType.ANALYTIC_INT: "Integer/Expr",
        ParamType.ANALYTIC_REAL: "Real/Expr",
    }
    return type_names.get(ptype, str(ptype))


def generate_stage_docs(registry: ParamRegistry, stage: Stage) -> str:
    """
    Generate documentation for a specific stage.

    Args:
        registry: The parameter registry
        stage: The stage to document

    Returns:
        Markdown documentation as a string
    """
    params = registry.get_params_by_stage(stage)

    lines = [
        f"# {stage.name} Parameters",
        "",
        f"*{len(params)} parameters*",
        "",
        "| Parameter | Type | Category | Description |",
        "|-----------|------|----------|-------------|",
    ]

    for name, param in sorted(params.items()):
        type_str = _type_to_str(param.param_type)
        cat = param.category or "-"
        desc = (param.description or "-").replace("|", "\\|")
        lines.append(f"| `{name}` | {type_str} | {cat} | {desc} |")

    return "\n".join(lines)


def generate_category_docs(registry: ParamRegistry, category: str) -> str:
    """
    Generate documentation for a specific category.

    Args:
        registry: The parameter registry
        category: The category to document

    Returns:
        Markdown documentation as a string
    """
    params = registry.get_params_by_category(category)

    lines = [
        f"# {category.replace('_', ' ').title()} Parameters",
        "",
        f"*{len(params)} parameters*",
        "",
        "| Parameter | Type | Stages | Description |",
        "|-----------|------|--------|-------------|",
    ]

    for name, param in sorted(params.items()):
        type_str = _type_to_str(param.param_type)
        stages_str = ", ".join(s.name for s in param.stages)
        desc = (param.description or "-").replace("|", "\\|")
        lines.append(f"| `{name}` | {type_str} | {stages_str} | {desc} |")

    return "\n".join(lines)


if __name__ == "__main__":
    from ..definitions import load_all_definitions
    from ..registry import REGISTRY

    load_all_definitions()
    print(generate_param_docs(REGISTRY))
