#!/usr/bin/env python3
import json

# 3D hypoelastic case with HLLD solver.
# Solid sphere in liquid hit by focused acoustic pulse.

config = {
    "run_time_info": "T",
    # Computational Domain
    "x_domain%beg": 0.0,
    "x_domain%end": 1.0,
    "y_domain%beg": 0.0,
    "y_domain%end": 1.0,
    "z_domain%beg": 0.0,
    "z_domain%end": 1.0,
    "m": 24,
    "n": 24,
    "p": 24,
    "cyl_coord": "F",
    "dt": 6.0e-6,
    "t_step_start": 0,
    "t_step_stop": 150,
    "t_step_save": 50,
    # Simulation Algorithm Parameters
    "num_patches": 2,
    "model_eqns": 2,
    "alt_soundspeed": "F",
    "num_fluids": 2,
    "mpp_lim": "T",
    "mixture_err": "F",
    "time_stepper": 1,
    "weno_order": 1,
    "weno_eps": 1.0e-20,
    "null_weights": "F",
    "mp_weno": "F",
    "riemann_solver": 4,
    "wave_speeds": 1,
    "avg_state": 2,
    "bc_x%beg": -3,
    "bc_x%end": -3,
    "bc_y%beg": -3,
    "bc_y%end": -3,
    "bc_z%beg": -3,
    "bc_z%end": -3,
    # Formatted Database Files Structure Parameters
    "format": 1,
    "precision": 2,
    "prim_vars_wrt": "T",
    "rho_wrt": "T",
    "parallel_io": "T",
    # Hypoelasticity
    "hypoelasticity": "T",
    "fd_order": 4,
    # Patch 1: Background liquid (3D box)
    "patch_icpp(1)%geometry": 9,
    "patch_icpp(1)%x_centroid": 0.5,
    "patch_icpp(1)%y_centroid": 0.5,
    "patch_icpp(1)%z_centroid": 0.5,
    "patch_icpp(1)%length_x": 1.0,
    "patch_icpp(1)%length_y": 1.0,
    "patch_icpp(1)%length_z": 1.0,
    "patch_icpp(1)%vel(1)": 0.0,
    "patch_icpp(1)%vel(2)": 0.0,
    "patch_icpp(1)%vel(3)": 0.0,
    "patch_icpp(1)%pres": 1e05,
    "patch_icpp(1)%tau_e(1)": 0.0,
    "patch_icpp(1)%alpha_rho(1)": 1000 * (1.0 - 1e-8),
    "patch_icpp(1)%alpha(1)": 1.0 - 1e-8,
    "patch_icpp(1)%alpha_rho(2)": 1000 * 1e-8,
    "patch_icpp(1)%alpha(2)": 1e-8,
    # Patch 2: Solid sphere
    "patch_icpp(2)%alter_patch(1)": "T",
    "patch_icpp(2)%geometry": 8,
    "patch_icpp(2)%x_centroid": 0.6,
    "patch_icpp(2)%y_centroid": 0.5,
    "patch_icpp(2)%z_centroid": 0.5,
    "patch_icpp(2)%radius": 0.1,
    "patch_icpp(2)%vel(1)": 0.0,
    "patch_icpp(2)%vel(2)": 0.0,
    "patch_icpp(2)%vel(3)": 0.0,
    "patch_icpp(2)%pres": 1e05,
    "patch_icpp(2)%tau_e(1)": 0.0,
    "patch_icpp(2)%alpha_rho(1)": 1000 * 1e-8,
    "patch_icpp(2)%alpha(1)": 1e-8,
    "patch_icpp(2)%alpha_rho(2)": 1000 * (1.0 - 1e-8),
    "patch_icpp(2)%alpha(2)": 1.0 - 1e-8,
    # Acoustic source (support 7 = 3D focused)
    "acoustic_source": "T",
    "num_source": 1,
    "acoustic(1)%support": 7,
    "acoustic(1)%loc(1)": 0.1,
    "acoustic(1)%loc(2)": 0.5,
    "acoustic(1)%loc(3)": 0.5,
    "acoustic(1)%pulse": 2,
    "acoustic(1)%npulse": 1,
    "acoustic(1)%mag": 1.0,
    "acoustic(1)%foc_length": 0.4,
    "acoustic(1)%aperture": 0.75,
    "acoustic(1)%gauss_sigma_time": 4e-5,
    "acoustic(1)%delay": 2e-4,
    # Fluids Physical Parameters
    "fluid_pp(1)%gamma": 1.0e00 / (4.4e00 - 1.0e00),
    "fluid_pp(1)%pi_inf": 4.4e00 * 5.57e08 / (4.4e00 - 1.0e00),
    "fluid_pp(1)%G": 0.0,
    "fluid_pp(2)%gamma": 1.0e00 / (4.4e00 - 1.0e00),
    "fluid_pp(2)%pi_inf": 4.4e00 * 5.57e08 / (4.4e00 - 1.0e00),
    "fluid_pp(2)%G": 1e9,
}

print(json.dumps(config, indent=4))
