"""
Case file to demonstrate and test the periodic collision of immersed boundaries.
This file was generated by Conrad Delgado as a minimum reproducer to prevent regression
of periodic immersed boundaries.
"""

import json
import math

import numpy as np

gam_a = 1.4

# particle diameter
D = 0.1
R = D / 2.0

# particle params
rho_s = 10.0
vol_s = 4.0 / 3.0 * np.pi * R**3
mass_s = rho_s * vol_s
N_s = 2

# fluid params
M = 2.0
Re = 500.0
P = 101325
rho = 1.225
v1 = M * np.sqrt(gam_a * P / rho)
mu = rho * v1 * D / Re

# timestep
dt = 1.0e-05
Nt = 50
t_save = 5

# grid
Nx = 31
Ny = 63
Nz = 31

# immersed boundary dictionary
ib_dict = {}
ib_dict.update(
    {
        f"patch_ib({1})%geometry": 8,
        f"patch_ib({1})%x_centroid": 0.0,
        f"patch_ib({1})%y_centroid": -2.1 * D,
        f"patch_ib({1})%z_centroid": 0.0,
        f"patch_ib({1})%vel(2)": -100.0,
        f"patch_ib({1})%radius": D / 2,
        f"patch_ib({1})%slip": "F",
        f"patch_ib({1})%moving_ibm": 2,
        f"patch_ib({1})%mass": mass_s,
        f"patch_ib({2})%geometry": 8,
        f"patch_ib({2})%x_centroid": 0.0,
        f"patch_ib({2})%y_centroid": 1.8 * D,
        f"patch_ib({2})%z_centroid": 0.0,
        f"patch_ib({2})%vel(2)": +100.0,
        f"patch_ib({2})%radius": D / 2,
        f"patch_ib({2})%slip": "F",
        f"patch_ib({2})%moving_ibm": 2,
        f"patch_ib({2})%mass": mass_s,
    }
)

# Configuring case dictionary
case_dict = {
    # Logistics
    "run_time_info": "T",
    # Computational Domain Parameters
    # x direction
    "x_domain%beg": -1.25 * D,
    "x_domain%end": 1.25 * D,
    # y direction
    "y_domain%beg": -2.5 * D,
    "y_domain%end": 2.5 * D,
    # z direction
    "z_domain%beg": -1.25 * D,
    "z_domain%end": 1.25 * D,
    "cyl_coord": "F",
    "m": Nx,
    "n": Ny,
    "p": Nz,
    "dt": dt,
    "t_step_start": 0,
    "t_step_stop": Nt,
    "t_step_save": t_save,
    # Simulation Algorithm Parameters
    # Only one patches are necessary, the air tube
    "num_patches": 1,
    # Use the 5 equation model
    "model_eqns": 2,
    # 6 equations model does not need the K \div(u) term
    "alt_soundspeed": "F",
    # One fluids: air
    "num_fluids": 1,
    # time step
    "mpp_lim": "F",
    # Correct errors when computing speed of sound
    "mixture_err": "T",
    # Use TVD RK3 for time marching
    "time_stepper": 3,
    # Reconstruct the primitive variables to minimize spurious
    # Use WENO5
    "weno_order": 5,
    "weno_eps": 1.0e-16,
    "weno_Re_flux": "T",
    "weno_avg": "T",
    "avg_state": 2,
    "null_weights": "F",
    "mp_weno": "T",
    "riemann_solver": 2,
    "wave_speeds": 1,
    # periodic bc
    "bc_x%beg": -3,
    "bc_x%end": -3,
    "bc_y%beg": -1,
    "bc_y%end": -1,
    "bc_z%beg": -3,
    "bc_z%end": -3,
    # Set IB to True and add 1 patch
    "ib": "T",
    "num_ibs": N_s,
    "viscous": "T",
    # Formatted Database Files Structure Parameters
    "format": 1,
    "precision": 2,
    "prim_vars_wrt": "T",
    "E_wrt": "T",
    "parallel_io": "T",
    "ib_state_wrt": "T",
    "fd_order": 4,
    # Patch: Constant Tube filled with air
    # Specify the cylindrical air tube grid geometry
    "patch_icpp(1)%geometry": 9,
    "patch_icpp(1)%x_centroid": 0.0,
    # Uniform medium density, centroid is at the center of the domain
    "patch_icpp(1)%y_centroid": 0.0,
    "patch_icpp(1)%z_centroid": 0.0,
    "patch_icpp(1)%length_x": 2.5 * D,
    "patch_icpp(1)%length_y": 5.0 * D,
    "patch_icpp(1)%length_z": 2.5 * D,
    # Specify the patch primitive variables
    "patch_icpp(1)%vel(1)": 0.0e00,
    "patch_icpp(1)%vel(2)": 0.0e00,
    "patch_icpp(1)%vel(3)": 0.0e00,
    "patch_icpp(1)%pres": P,
    "patch_icpp(1)%alpha_rho(1)": rho,
    "patch_icpp(1)%alpha(1)": 1.0e00,
    # Patch: Sphere Immersed Boundary
    # Fluids Physical Parameters
    "fluid_pp(1)%gamma": 1.0e00 / (gam_a - 1.0e00),  # 2.50(Not 1.40)
    "fluid_pp(1)%pi_inf": 0,
    "fluid_pp(1)%Re(1)": 1.0 / mu,
    "collision_model": 1,  # soft-sphere collision model
    "ib_coefficient_of_friction": 0.1,
    "collision_time": 20.0 * dt,
    "coefficient_of_restitution": 0.9,  # almost perfectly elastic
}

case_dict.update(ib_dict)

print(json.dumps(case_dict))
