"""
MFC Case Parameter Types for IDE Auto-completion.

This file is auto-generated by ./mfc.sh generate --json-schema
Provides TypedDict for IDE auto-completion in Python case files.

Usage:
    from mfc.params.case_types import MFCParams

    case: MFCParams = {
        'm': 200,
        'weno_order': 5,
        # IDE provides auto-completion for keys!
    }

Includes 209 parameters with valid Python identifiers.
For indexed parameters (patch_icpp, fluid_pp, etc.), use:
    ./mfc.sh params <query>
"""

from typing import TypedDict, Union, Any


class MFCParams(TypedDict, total=False):
    """
    MFC simulation case parameters.
    
    All fields are optional (total=False).
    Use ./mfc.sh params <name> for parameter documentation.
    """
    # --- Integer parameters ---
    adap_dt_max_iters: int  # Maximum iterations for adaptive time stepping
    avg_state: int  # Average state for Riemann solver (1=Roe, 2=arithmetic)
    bubble_model: int  # Bubble dynamics model (1=Gilmore, 2=Keller-Miksis, 3=Rayleigh-Plesset)
    dist_type: int  # Distribution type for polydisperse bubbles
    elliptic_smoothing_iters: int  # Number of elliptic smoothing iterations
    fd_order: int  # Finite difference order for gradients
    flux_lim: int  # Flux limiter type
    format: int  # Output format (1=Silo, 2=binary)
    igr_iter_solver: int  # IGR iterative solver type
    igr_order: int  # Implicit gradient reconstruction order
    loops_x: int  # Number of times to apply grid stretching in x
    loops_y: int  # Number of times to apply grid stretching in y
    loops_z: int  # Number of times to apply grid stretching in z
    low_Mach: int  # Low Mach number correction
    m: int  # Number of grid cells in the x-direction
    mixlayer_perturb_nk: int  # Number of perturbation modes for mixing layer
    model_eqns: int  # Model equations (1=gamma-law, 2=5-eq, 3=6-eq, 4=4-eq)
    muscl_lim: int  # MUSCL limiter type
    muscl_order: int  # Order of MUSCL reconstruction
    n: int  # Number of grid cells in the y-direction
    n_start: int  # Starting time step index
    n_start_old: int  # Starting index from previous simulation
    num_bc_patches: int  # Number of boundary condition patches
    num_fluids: int  # Number of fluid components
    num_ibs: int  # Number of immersed boundary patches
    num_igr_iters: int  # Number of IGR iterations
    num_igr_warm_start_iters: int  # Number of IGR warm-start iterations
    num_integrals: int  # Number of integral regions
    num_patches: int  # Number of initial condition patches
    num_probes: int  # Number of probe points
    num_source: int  # Number of acoustic sources
    nv_uvm_igr_temps_on_gpu: int  # Store IGR temporaries on GPU
    p: int  # Number of grid cells in the z-direction
    perturb_flow_fluid: int  # Fluid index for flow perturbation
    perturb_sph_fluid: int  # Fluid index for spherical perturbation
    precision: int  # Output precision (1=single, 2=double)
    recon_type: int  # Reconstruction type (1=WENO, 2=MUSCL)
    relax_model: int  # Relaxation model type
    riemann_solver: int  # Riemann solver (1=HLL, 2=HLLC, 3=exact)
    t_step_old: int  # Time step to restart from
    t_step_print: int  # Time step interval for printing info
    t_step_save: int  # Time step interval for saving data
    t_step_start: int  # Starting time step index
    t_step_stop: int  # Ending time step index
    thermal: int  # Thermal model selection
    time_stepper: int  # Time integration scheme (1=Euler, 2=TVD-RK2, 3=TVD-RK3, 4=RK4, 5=RK5)
    wave_speeds: int  # Wave speed estimates (1=direct, 2=pressure)
    weno_order: int  # Order of WENO reconstruction (1, 3, 5, or 7)

    # --- Real/float parameters ---
    Bx0: float  # Background magnetic field in x-direction
    R0ref: float  # Reference bubble radius
    a_x: float  # Rate of grid stretching in the x-direction
    a_y: float  # Rate of grid stretching in the y-direction
    a_z: float  # Rate of grid stretching in the z-direction
    adap_dt_tol: float  # Tolerance for adaptive time stepping
    alf_factor: float  # Artificial viscosity factor
    alpha_bar: float  # Average volume fraction
    cfl_max: float  # Maximum allowed CFL number
    cfl_target: float  # Target CFL number for adaptive time stepping
    cont_damage_s: float  # Continuum damage shape parameter
    dt: float  # Time step size
    fluid_rho: float  # Reference fluid density
    g_x: float  # Body force parameter g in x-direction
    g_y: float  # Body force parameter g in y-direction
    g_z: float  # Body force parameter g in z-direction
    ic_beta: float  # Interface compression beta
    ic_eps: float  # Interface compression epsilon
    k_x: float  # Body force parameter k in x-direction
    k_y: float  # Body force parameter k in y-direction
    k_z: float  # Body force parameter k in z-direction
    mixlayer_domain: float  # Mixing layer domain size
    mixlayer_perturb_k0: float  # Base wavenumber for mixing layer perturbation
    mixlayer_vel_coef: float  # Velocity coefficient for mixing layer
    nb: float  # Number of bubble bins for polydisperse model
    p_x: float  # Body force parameter p in x-direction
    p_y: float  # Body force parameter p in y-direction
    p_z: float  # Body force parameter p in z-direction
    palpha_eps: float  # Volume fraction epsilon for pressure relaxation
    perturb_flow_mag: float  # Magnitude of flow perturbation
    pi_fac: float  # Pi infinity factor
    poly_sigma: float  # Polydisperse distribution standard deviation
    pref: float  # Reference pressure
    ptgalpha_eps: float  # Volume fraction epsilon for PTG relaxation
    rhoRV: float  # Bubble radius-velocity correlation
    rhoref: float  # Reference density
    schlieren_alpha: float  # Schlieren alpha coefficient
    sigR: float  # Bubble radius standard deviation
    sigV: float  # Bubble velocity standard deviation
    sigma: float  # Surface tension coefficient
    t_save: float  # Time interval for saving data
    t_stop: float  # Simulation stop time
    t_tol: float  # Time tolerance
    tau_star: float  # Non-dimensional relaxation time
    teno_CT: float  # TENO cutoff parameter
    w_x: float  # Body force parameter w in x-direction
    w_y: float  # Body force parameter w in y-direction
    w_z: float  # Body force parameter w in z-direction
    weno_eps: float  # WENO epsilon parameter for smoothness
    wenoz_q: float  # WENO-Z power parameter
    x_a: float  # Start of stretching in negative x-direction
    x_b: float  # Start of stretching in positive x-direction
    y_a: float  # Start of stretching in negative y-direction
    y_b: float  # Start of stretching in positive y-direction
    z_a: float  # Start of stretching in negative z-direction
    z_b: float  # Start of stretching in positive z-direction

    # --- String/logical parameters ---
    E_wrt: str  # Write energy field
    acoustic_source: str  # Enable acoustic source terms
    adap_dt: str  # Enable adaptive time stepping
    adv_n: str  # Enable advection of number density
    alpha_rho_wrt: str  # Write partial density field
    alpha_wrt: str  # Write volume fraction field
    alt_soundspeed: str  # Use alternative sound speed formulation
    bf_x: str  # Enable body force in x-direction
    bf_y: str  # Enable body force in y-direction
    bf_z: str  # Enable body force in z-direction
    bubbles_euler: str  # Enable Euler-Euler bubble model
    bubbles_lagrange: str  # Enable Lagrangian bubble tracking
    c_wrt: str  # Write sound speed field
    cantera_file: str  # Cantera mechanism file for chemistry
    case_dir: str  # Case directory path
    cf_wrt: str  # Write color function field
    cfl_adap_dt: str  # Enable adaptive time stepping based on CFL
    cfl_const_dt: str  # Use constant CFL for time stepping
    cfl_dt: str  # Enable CFL-based time stepping
    chem_wrt_T: str  # Write temperature field for chemistry
    chemistry: str  # Enable chemical reactions
    cons_vars_wrt: str  # Write conservative variables
    cont_damage: str  # Enable continuum damage model
    cyl_coord: str  # Enable cylindrical coordinates (2D: axisymmetric, 3D: cylindrical)
    down_sample: str  # Enable output downsampling
    elliptic_smoothing: str  # Enable elliptic smoothing
    fft_wrt: str  # Enable FFT output
    file_per_process: str  # Write separate file per MPI process
    flux_wrt: str  # Write flux to output
    gamma_wrt: str  # Write gamma field
    heat_ratio_wrt: str  # Write heat capacity ratio field
    hyperelasticity: str  # Enable hyperelastic model
    hypoelasticity: str  # Enable hypoelastic model
    ib: str  # Enable immersed boundary method
    igr: str  # Enable implicit gradient reconstruction
    igr_pres_lim: str  # Enable IGR pressure limiting
    int_comp: str  # Enable interface compression
    integral_wrt: str  # Write integral data
    kappa_wrt: str  # Write curvature field
    lag_betaC_wrt: str  # Write Lagrangian betaC field
    lag_betaT_wrt: str  # Write Lagrangian betaT field
    lag_db_wrt: str  # Write Lagrangian db field
    lag_dphidt_wrt: str  # Write Lagrangian dphidt field
    lag_header: str  # Enable Lagrangian output header
    lag_id_wrt: str  # Write Lagrangian id field
    lag_mg_wrt: str  # Write Lagrangian mg field
    lag_mv_wrt: str  # Write Lagrangian mv field
    lag_pos_prev_wrt: str  # Write Lagrangian pos_prev field
    lag_pos_wrt: str  # Write Lagrangian pos field
    lag_pres_wrt: str  # Write Lagrangian pres field
    lag_r0_wrt: str  # Write Lagrangian r0 field
    lag_rad_wrt: str  # Write Lagrangian rad field
    lag_rmax_wrt: str  # Write Lagrangian rmax field
    lag_rmin_wrt: str  # Write Lagrangian rmin field
    lag_rvel_wrt: str  # Write Lagrangian rvel field
    lag_txt_wrt: str  # Write Lagrangian txt field
    lag_vel_wrt: str  # Write Lagrangian vel field
    liutex_wrt: str  # Write Liutex vortex field
    mapped_weno: str  # Enable mapped WENO scheme
    mhd: str  # Enable magnetohydrodynamics
    mixlayer_perturb: str  # Enable mixing layer perturbation
    mixlayer_vel_profile: str  # Enable mixing layer velocity profile
    mixture_err: str  # Enable mixture error checking
    mom_wrt: str  # Write mom to output
    mp_weno: str  # Enable monotonicity-preserving WENO
    mpp_lim: str  # Enable mixture pressure positivity limiter
    null_weights: str  # Allow null WENO weights
    nv_uvm_out_of_core: str  # Enable NVIDIA UVM out-of-core
    nv_uvm_pref_gpu: str  # Prefer GPU for NVIDIA UVM
    old_grid: str  # Use grid from previous simulation
    old_ic: str  # Use initial conditions from previous simulation
    omega_wrt: str  # Write vorticity field
    output_partial_domain: str  # Enable partial domain output
    parallel_io: str  # Enable parallel I/O
    perturb_flow: str  # Enable flow perturbation
    perturb_sph: str  # Enable spherical perturbation
    pi_inf_wrt: str  # Write pi_inf field
    polydisperse: str  # Enable polydisperse bubble distribution
    polytropic: str  # Enable polytropic gas behavior for bubbles
    powell: str  # Enable Powell source terms for MHD
    pre_stress: str  # Enable pre-stress initialization
    pres_inf_wrt: str  # Write reference pressure field
    pres_wrt: str  # Write pressure field
    prim_vars_wrt: str  # Write primitive variables
    probe_wrt: str  # Write probe data
    qbmm: str  # Enable quadrature-based moment method
    qm_wrt: str  # Write Q-criterion field
    rdma_mpi: str  # Enable RDMA for MPI communication (GPUs)
    relativity: str  # Enable special relativity
    relax: str  # Enable relaxation terms
    rho_wrt: str  # Write density field
    run_time_info: str  # Output run-time information
    schlieren_wrt: str  # Write schlieren images
    sim_data: str  # Enable simulation data output
    simplex_perturb: str  # Enable simplex noise perturbation
    stretch_x: str  # Enable grid stretching in the x-direction
    stretch_y: str  # Enable grid stretching in the y-direction
    stretch_z: str  # Enable grid stretching in the z-direction
    surface_tension: str  # Enable surface tension effects
    teno: str  # Enable TENO scheme
    vel_wrt: str  # Write velocity field
    viscous: str  # Enable viscous effects
    weno_Re_flux: str  # Enable WENO for viscous fluxes
    weno_avg: str  # Enable WENO averaging
    wenoz: str  # Enable WENO-Z scheme
