"""Layout of the state vector (eqn_idx and sys_size), defined once.

Each model appends fields in order; a field occupies `size` slots (one if `size` is None) when its
`when` condition holds. Sizes, conditions, and alias values are Python expressions over the
s_initialize_eqn_idx inputs and over earlier fields (`adv.end`). They are both translated to the
Fortran of s_initialize_eqn_idx (fortran_layout) and evaluated for a given case (evaluate_layout),
so the runtime layout and a case-optimized sys_size cannot disagree.
"""

import ast
from dataclasses import dataclass
from typing import Dict, List, Optional


@dataclass(frozen=True)
class Field:
    name: str
    size: Optional[str] = None  # None: a single index (eqn_idx%name); else a range (eqn_idx%name%beg:end)
    when: Optional[str] = None


@dataclass(frozen=True)
class Alias:
    name: str
    value: str
    when: Optional[str] = None


HEAD = [Field("mom", "num_vels"), Field("E")]

MODELS: Dict[str, List] = {
    "gamma_law": [Field("cont", "1"), *HEAD, Field("adv", "2"), Alias("gamma", "adv.beg"), Alias("pi_inf", "adv.end")],
    "5eq": [
        Field("cont", "num_fluids"),
        *HEAD,
        Field("adv", "num_fluids - 1 if igr else num_fluids"),
        Alias("alf", "adv.end if bubbles_euler else 1"),
        Field("bub", "nb_in*nmom_in if qbmm else (2 if polytropic else 4)*nb_in", "bubbles_euler"),
        Field("n", None, "bubbles_euler and adv_n"),
        Field("B", "2 if n == 0 else 3", "mhd"),
    ],
    "6eq": [
        Field("cont", "num_fluids"),
        *HEAD,
        Field("adv", "num_fluids"),
        Alias("alf", "adv.end", "six_eqn_alf_is_advected"),
        Field("int_en", "num_fluids"),
    ],
}

# Appended after the model fields: for the five- and six-equation models, then for every model.
MULTIPHASE = [
    Field("stress", "num_dims*(num_dims + 1)//2 + (1 if cyl_coord else 0)", "hypoelasticity"),
    Field("c", None, "surface_tension"),
    Field("damage", None, "cont_damage"),
    Field("psi", None, "hyper_cleaning"),
]
ALL_MODELS = [Field("species", "num_species", "chemistry")]


class _ToFortran(ast.NodeVisitor):
    OPS = {ast.Add: "+", ast.Sub: "-", ast.Mult: "*", ast.FloorDiv: "/", ast.Eq: "==", ast.NotEq: "/="}

    def visit_Expression(self, node):
        return self.visit(node.body)

    def visit_Name(self, node):
        return {"True": ".true.", "False": ".false."}.get(node.id, node.id)

    def visit_Constant(self, node):
        return {True: ".true.", False: ".false."}[node.value] if isinstance(node.value, bool) else str(node.value)

    def visit_Attribute(self, node):
        return f"eqn_idx%{node.value.id}%{node.attr}"

    def visit_BinOp(self, node):
        return f"({self.visit(node.left)} {self.OPS[type(node.op)]} {self.visit(node.right)})"

    def visit_Compare(self, node):
        return f"({self.visit(node.left)} {self.OPS[type(node.ops[0])]} {self.visit(node.comparators[0])})"

    def visit_BoolOp(self, node):
        op = " .and. " if isinstance(node.op, ast.And) else " .or. "
        return "(" + op.join(self.visit(v) for v in node.values) + ")"

    def visit_UnaryOp(self, node):
        return f"(.not. {self.visit(node.operand)})"

    def visit_IfExp(self, node):
        return f"merge({self.visit(node.body)}, {self.visit(node.orelse)}, {self.visit(node.test)})"

    def generic_visit(self, node):
        raise ValueError(f"eqn_layout: unsupported expression node {type(node).__name__}")


def _f(expr: str) -> str:
    """Translate a layout expression to Fortran."""
    return _ToFortran().visit(ast.parse(expr, mode="eval"))


def _fields_fortran(fields, ind: str) -> List[str]:
    out = []
    for f in fields:
        body = []
        if isinstance(f, Alias):
            body.append(f"eqn_idx%{f.name} = {_f(f.value)}")
        elif f.size is None:
            body += [f"eqn_idx%{f.name} = sys_size + 1", f"sys_size = eqn_idx%{f.name}"]
        else:
            body += [f"eqn_idx%{f.name}%beg = sys_size + 1", f"eqn_idx%{f.name}%end = sys_size + {_f(f.size)}", f"sys_size = eqn_idx%{f.name}%end"]
        if f.when:
            cond = _f(f.when)
            out += [f"{ind}if ({cond[1:-1] if cond.startswith('(') else cond}) then", *(f"{ind}    {b}" for b in body), f"{ind}end if"]
        else:
            out += [f"{ind}{b}" for b in body]
    return out


def fortran_layout() -> str:
    """Fortran statements setting eqn_idx and sys_size (included by s_initialize_eqn_idx)."""
    lines = ["! Generated by toolchain/mfc/params/eqn_layout.py. Do not edit.", "sys_size = 0"]
    for i, (model, fields) in enumerate(MODELS.items()):
        lines.append(f"{'if' if i == 0 else 'else if'} (model_eqns == model_eqns_{model}) then")
        lines += _fields_fortran(fields, "    ")
    lines.append("end if")
    lines.append("if (model_eqns == model_eqns_5eq .or. model_eqns == model_eqns_6eq) then")
    lines += _fields_fortran(MULTIPHASE, "    ")
    lines.append("end if")
    lines += _fields_fortran(ALL_MODELS, "")
    return "\n".join(lines) + "\n"


class _Ranges(dict):
    """Lets layout expressions read earlier ranges as `adv.beg` / `adv.end`."""

    def __getattr__(self, key):
        return self[key]


def evaluate_layout(inputs: Dict) -> Dict:
    """Evaluate the layout for given inputs (model_eqns as 'gamma_law'/'5eq'/'6eq', flags, counts).

    Returns {"sys_size": int, field: index or (beg, end), alias: index}.
    """
    env = dict(inputs)
    out: Dict = {}
    size = 0

    def run(fields):
        nonlocal size
        for f in fields:
            if f.when and not eval(f.when, {}, env):
                continue
            if isinstance(f, Alias):
                out[f.name] = eval(f.value, {}, env)
                continue
            beg, end = size + 1, size + (1 if f.size is None else int(eval(f.size, {}, env)))
            out[f.name] = beg if f.size is None else (beg, end)
            if f.size is not None:  # only ranges are referenced (adv.end); `n` is also the grid size
                env[f.name] = _Ranges(beg=beg, end=end)
            size = end

    run(MODELS[inputs["model_eqns"]])
    if inputs["model_eqns"] in ("5eq", "6eq"):
        run(MULTIPHASE)
    run(ALL_MODELS)
    out["sys_size"] = size
    return out
