"""Guards the per-fluid equation-of-state selector.

The eos_* constants are generated by generate_constants_fpp from EOS_FAMILIES (compound registry
keys carry a "fortran_prefix" so fluid_pp(1)%eos's names become standalone eos_<name> constants).
Asserting the generator agrees with the registry it was generated from would be circular, so the
tests below check the emitter's naming/values directly and cross-check against actual Fortran usage
instead of re-deriving from the same registry.
"""

import re

from ..case_validator import CaseValidator
from ..params.definitions import CONSTRAINTS
from ..params.generators.fortran_gen import generate_constants_fpp
from ..params.namelist_parser import get_mfc_root

EOS = CONSTRAINTS["fluid_pp(1)%eos"]["names"]

# Values the hand-written m_constants.fpp block carried before this generator emitted them.
_EXPECTED_EOS_CONSTANT_LINES = {
    "integer, parameter :: eos_stiffened_gas = 1",
    "integer, parameter :: eos_ideal_gas = 2",
    "integer, parameter :: eos_mie_gruneisen = 3",
    "integer, parameter :: eos_jwl = 4",
    "integer, parameter :: eos_vinet = 5",
}

# eos_* identifiers that appear in src/ but are not registry-derived selector constants:
# eos_coeffs/eos_coefficients are a variable/type name, eos_rk4_steps is an unrelated,
# hand-written RK4 step count (not a family selector, so not in EOS_FAMILIES).
_NON_FAMILY_EOS_IDENTIFIERS = {"eos_coeffs", "eos_coefficients", "eos_rk4_steps"}

_EOS_IDENTIFIER_RE = re.compile(r"\b(eos_[a-zA-Z0-9_]+)\b")


def _errors(**overrides):
    params = {"num_fluids": 1, "fluid_pp(1)%gamma": 2.5, "fluid_pp(1)%pi_inf": 0.0}
    params.update(overrides)
    validator = CaseValidator(params)
    validator.check_eos_selector()
    return validator.errors


def test_generate_constants_fpp_emits_one_line_per_eos_family():
    out = generate_constants_fpp()
    lines = {line for line in out.splitlines() if "eos_" in line}
    assert lines == _EXPECTED_EOS_CONSTANT_LINES


def _eos_identifiers_referenced_under_src():
    referenced = set()
    src = get_mfc_root() / "src"
    for path in list(src.rglob("*.fpp")) + list(src.rglob("*.f90")):
        for line in path.read_text().splitlines():
            code = line.split("!", 1)[0]  # drop comments; identifiers, not doc prose, matter here
            referenced.update(_EOS_IDENTIFIER_RE.findall(code))
    return referenced


def test_every_eos_identifier_in_src_is_generated_or_known_non_family():
    generated = {f"eos_{name}" for name in EOS}
    referenced = _eos_identifiers_referenced_under_src()
    unaccounted = referenced - generated - _NON_FAMILY_EOS_IDENTIFIERS
    assert not unaccounted, f"eos_* symbol(s) referenced in src/ but absent from EOS_FAMILIES: {sorted(unaccounted)}"


def test_stiffened_gas_accepts_stiffness():
    assert _errors(**{"fluid_pp(1)%eos": EOS["stiffened_gas"], "fluid_pp(1)%pi_inf": 1.0e5}) == []


def test_ideal_gas_owns_no_stiffness_parameter():
    assert _errors(**{"fluid_pp(1)%eos": EOS["ideal_gas"], "fluid_pp(1)%pi_inf": None}) == []
    errors = _errors(**{"fluid_pp(1)%eos": EOS["ideal_gas"], "fluid_pp(1)%pi_inf": 0.0})
    assert len(errors) == 1 and "do not set fluid_pp(1)%pi_inf" in errors[0]


def test_ideal_gas_rejects_nonzero_stiffness():
    errors = _errors(**{"fluid_pp(1)%eos": EOS["ideal_gas"], "fluid_pp(1)%pi_inf": 1.0e5})
    assert len(errors) == 1 and "pi_inf" in errors[0]


def test_value_outside_the_enumeration_is_rejected():
    # choices are enforced by validate_constraints, a different layer, so the membership
    # check here is not redundant.
    assert len(_errors(**{"fluid_pp(1)%eos": 99})) == 1


def test_unset_selector_is_skipped():
    assert _errors() == []
