# mfc_cpu.sub

executable = mfc_gpu_bench.sh
arguments = $(Process)

log = mfc_cpu_$(Cluster)_$(Process).log
error = mfc_cpu_$(Cluster)_$(Process).err
output = mfc_cpu_$(Cluster)_$(Process).out

+JobDurationCategory = "Medium"

requirements = (OSGVO_OS_STRING == "Ubuntu 22")
request_cpus = 4
request_gpus = 4
request_memory = 16GB
request_disk = 32GB
gpus_minimum_memory = <quantity in MB>
gpus_minimum_capability = 7.0
gpus_minimum_memory = 40000

queue 1