! This file was generated by MFC. It is only used if the --hard-code option is
! passed to ./mfc.sh run, enabling a GPU-oriented optimization that hard-codes
! some case parameters in order to improve runtime performance.

#:set MFC_HARD_CODE = False
