#!/usr/bin/env python3
# WARNING: This file was generated by Claude Code
# Parameterized 3D tri-periodic Euler-Lagrange case for isolating why
# moving bubbles + two-way coupling give rank-count-dependent results.
#
# A cubic lattice of bubbles sits in a quiescent-to-slowly-advecting host;
# a central high-pressure sphere drives radial dynamics and translation.
# Every physics axis under investigation is a CLI flag so the same case
# file covers the whole bisection matrix:
#
#   --no-bubbles 1                 pure Eulerian control (M0)
#   --vel-model {0,1,2}            0=static, 1=follow fluid, 2=drag (M1 vs M2/M3)
#   --solver-approach {1,2}        1=one-way, 2=two-way (M2 vs M3)
#   --bubble-model {0,1,2,3}       0=rigid particle .. 2=Keller-Miksis (default)
#   --perturb 1 --perturb-amp A    add ~A random perturbation to every bubble's
#                                  position, radius, and rdot (chaos baseline)
#   --single-bubble 1 --bub-x X .. one bubble at an exact position (boundary
#                                  straddle / migration forensics)
#
# Bubble ICs are written at full double precision (%.17e) so 1e-14
# perturbations survive the text round trip (same rationale as
# 3D_lagrange_advection/case_perturbed.py).
import argparse
import json
import math
import os
import sys

import numpy as np

_parser = argparse.ArgumentParser(description="EL coupling bisection matrix case.")
_parser.add_argument("--mfc", default=None, help=argparse.SUPPRESS)  # injected by mfc.sh; ignored
_parser.add_argument("--no-bubbles", type=int, choices=(0, 1), default=0)
_parser.add_argument("--vel-model", type=int, choices=(0, 1, 2), default=2)
_parser.add_argument("--drag-model", type=int, default=1)
_parser.add_argument("--solver-approach", type=int, choices=(1, 2), default=2)
_parser.add_argument("--bubble-model", type=int, choices=(0, 1, 2, 3), default=2)
_parser.add_argument("--cluster-type", type=int, default=1)
_parser.add_argument("--smooth-type", type=int, choices=(1, 2), default=1)
_parser.add_argument("--adap-dt", type=int, choices=(0, 1), default=0)
_parser.add_argument("--kahan", type=int, choices=(-1, 0, 1), default=-1, help="-1: leave code default")
_parser.add_argument("--nbubs-side", type=int, default=4)
_parser.add_argument("--pres-ratio", type=float, default=10.0)
_parser.add_argument("--u-adv", type=float, default=0.05, help="uniform diagonal background velocity")
_parser.add_argument("--steps", type=int, default=20)
_parser.add_argument("--save-every", type=int, default=1)
_parser.add_argument("--perturb", type=int, choices=(0, 1), default=0)
_parser.add_argument("--perturb-amp", type=float, default=1.0e-14)
_parser.add_argument("--perturb-seed", type=int, default=2024)
_parser.add_argument("--single-bubble", type=int, choices=(0, 1), default=0)
_parser.add_argument("--bub-x", type=float, default=0.35)
_parser.add_argument("--bub-y", type=float, default=0.0)
_parser.add_argument("--bub-z", type=float, default=0.0)
_parser.add_argument("--bub-r", type=float, default=0.03)
_parser.add_argument("--bub-vel", type=float, default=0.0, help="initial particle velocity (all 3 components; single-bubble mode)")
_args, _ = _parser.parse_known_args()

# Reference values for nondimensionalization (match the other EL cases)
L0 = 1e-3
rho0 = 950
c0 = 1449.0
p0 = rho0 * c0 * c0
T0 = 298

# Domain: cube [-1, 1] nondim
xb, xe = -1.0, 1.0
yb, ye = -1.0, 1.0
zb, ze = -1.0, 1.0

# Host (water)
gamma_host = 6.12
pi_inf_host = 3.43e8
mu_host = 0.001
rho_host = 950

# Bubble gas/vapor properties
R_uni = 8314
MW_g = 28.0
MW_v = 18.0
gamma_g = 1.4
gamma_v = 1.333
pv = 2350
cp_g = 1.0e3
cp_v = 2.1e3
k_g = 0.025
k_v = 0.02
diffVapor = 2.5e-5
sigBubble = 0.020
mu_g = 1.48e-5
rho_g = 1

patm = 1e5
pres = patm / p0
rho_host_nd = rho_host / rho0
rho_g_nd = rho_g / rho0

# 50 cells/dir: the MPI decomposition needs >= num_stcls_min*weno_order = 25
# cells per rank per split direction, so 50^3 is the smallest cube that
# supports 1, 2, and 8 (=2x2x2) ranks with WENO5.
Ncells = 50
m = n = p = Ncells - 1
dt = 0.02

N_side = _args.nbubs_side
nBubs = 1 if _args.single_bubble else N_side**3
R_median_nd = 0.02
sigma_ln = 0.3

data = {
    "run_time_info": "T",
    "x_domain%beg": xb,
    "x_domain%end": xe,
    "y_domain%beg": yb,
    "y_domain%end": ye,
    "z_domain%beg": zb,
    "z_domain%end": ze,
    "m": m,
    "n": n,
    "p": p,
    "dt": dt,
    "t_step_start": 0,
    "t_step_stop": _args.steps,
    "t_step_save": _args.save_every,
    "model_eqns": 2,
    "alt_soundspeed": "F",
    "mixture_err": "F",
    "mpp_lim": "T",
    "time_stepper": 3,
    "weno_order": 5,
    "mapped_weno": "T",
    "mp_weno": "F",
    "avg_state": 2,
    "weno_eps": 1e-16,
    "riemann_solver": 2,
    "wave_speeds": 1,
    "bc_x%beg": -1,
    "bc_x%end": -1,
    "bc_y%beg": -1,
    "bc_y%end": -1,
    "bc_z%beg": -1,
    "bc_z%end": -1,
    "num_patches": 2,
    "num_fluids": 2,
    "format": 1,
    "precision": 2,
    "prim_vars_wrt": "T",
    "parallel_io": "T",
    # Fluid 1: water host
    "fluid_pp(1)%gamma": 1.0 / (gamma_host - 1.0),
    "fluid_pp(1)%pi_inf": gamma_host * (pi_inf_host / p0) / (gamma_host - 1.0),
    # Fluid 2: gas
    "fluid_pp(2)%gamma": 1.0 / (gamma_g - 1.0),
    "fluid_pp(2)%pi_inf": 0.0,
    # Viscosity
    "viscous": "T",
    "fluid_pp(1)%Re(1)": 1.0 / (mu_host / (rho0 * c0 * L0)),
    "fluid_pp(2)%Re(1)": 1.0 / (mu_g / (rho0 * c0 * L0)),
    # Patch 1: uniform background flow along (1,1,1)
    "patch_icpp(1)%geometry": 9,
    "patch_icpp(1)%x_centroid": (xb + xe) / 2,
    "patch_icpp(1)%y_centroid": (yb + ye) / 2,
    "patch_icpp(1)%z_centroid": (zb + ze) / 2,
    "patch_icpp(1)%length_x": (xe - xb),
    "patch_icpp(1)%length_y": (ye - yb),
    "patch_icpp(1)%length_z": (ze - zb),
    "patch_icpp(1)%vel(1)": _args.u_adv,
    "patch_icpp(1)%vel(2)": _args.u_adv,
    "patch_icpp(1)%vel(3)": _args.u_adv,
    "patch_icpp(1)%pres": pres,
    "patch_icpp(1)%alpha_rho(1)": rho_host_nd,
    "patch_icpp(1)%alpha_rho(2)": 0,
    "patch_icpp(1)%alpha(1)": 1,
    "patch_icpp(1)%alpha(2)": 0,
    # Patch 2: central high-pressure sphere (drives dynamics)
    "patch_icpp(2)%geometry": 8,
    "patch_icpp(2)%alter_patch(1)": "T",
    "patch_icpp(2)%x_centroid": 0,
    "patch_icpp(2)%y_centroid": 0,
    "patch_icpp(2)%z_centroid": 0,
    "patch_icpp(2)%radius": 0.3,
    "patch_icpp(2)%vel(1)": _args.u_adv,
    "patch_icpp(2)%vel(2)": _args.u_adv,
    "patch_icpp(2)%vel(3)": _args.u_adv,
    "patch_icpp(2)%pres": _args.pres_ratio * pres,
    "patch_icpp(2)%alpha_rho(1)": rho_host_nd,
    "patch_icpp(2)%alpha_rho(2)": 0,
    "patch_icpp(2)%alpha(1)": 1,
    "patch_icpp(2)%alpha(2)": 0,
}

if not _args.no_bubbles:
    data.update(
        {
            # Bubble physical parameters
            "bub_pp%R0ref": 1.0,
            "bub_pp%p0ref": 1.0,
            "bub_pp%rho0ref": 1.0,
            "bub_pp%T0ref": 1.0,
            "bub_pp%ss": sigBubble / (rho0 * L0 * c0 * c0),
            "bub_pp%pv": pv / p0,
            "bub_pp%vd": diffVapor / (L0 * c0),
            "bub_pp%mu_l": mu_host / (rho0 * L0 * c0),
            "bub_pp%gam_v": gamma_v,
            "bub_pp%gam_g": gamma_g,
            "bub_pp%M_v": MW_v,
            "bub_pp%M_g": MW_g,
            "bub_pp%k_v": k_v * (T0 / (L0 * rho0 * c0 * c0 * c0)),
            "bub_pp%k_g": k_g * (T0 / (L0 * rho0 * c0 * c0 * c0)),
            "bub_pp%cp_v": cp_v * (T0 / (c0 * c0)),
            "bub_pp%cp_g": cp_g * (T0 / (c0 * c0)),
            "bub_pp%R_v": (R_uni / MW_v) * (T0 / (c0 * c0)),
            "bub_pp%R_g": (R_uni / MW_g) * (T0 / (c0 * c0)),
            # Lagrangian bubbles
            "bubbles_lagrange": "T",
            "fd_order": 4,
            "bubble_model": _args.bubble_model,
            "thermal": 3,
            "polytropic": "F",
            "lag_params%nBubs_glb": nBubs,
            "lag_params%vel_model": _args.vel_model,
            "lag_params%drag_model": _args.drag_model,
            "lag_params%solver_approach": _args.solver_approach,
            "lag_params%cluster_type": _args.cluster_type,
            "lag_params%pressure_corrector": "F",
            "lag_params%smooth_type": _args.smooth_type,
            "lag_params%epsilonb": 1.0,
            "lag_params%valmaxvoid": 0.9,
            "lag_params%write_bubbles": "T",
            "lag_params%write_bubbles_stats": "F",
            "lag_params%write_void_evol": "F",
        }
    )
    if _args.adap_dt:
        data["adap_dt"] = "T"
    if _args.kahan >= 0:
        data["lag_params%kahan_summation"] = "T" if _args.kahan else "F"


def write_lag_bubbles_file():
    if _args.single_bubble:
        x_pos = np.array([_args.bub_x])
        y_pos = np.array([_args.bub_y])
        z_pos = np.array([_args.bub_z])
        R = np.array([_args.bub_r])
    else:
        # Lattice over the inner [-0.5, 0.5]^3 so bubbles straddle the
        # pressure-sphere edge (r=0.3): differential forcing => motion.
        s = 1.0 / N_side
        coords = -0.5 + 0.5 * s + np.arange(N_side) * s
        X, Y, Z = np.meshgrid(coords, coords, coords, indexing="ij")
        x_pos, y_pos, z_pos = X.flatten(), Y.flatten(), Z.flatten()
        rng = np.random.default_rng(seed=42)
        R = rng.lognormal(mean=math.log(R_median_nd), sigma=sigma_ln, size=nBubs)
        R = np.minimum(R, 0.045)

    vx = np.full(nBubs, _args.bub_vel if _args.single_bubble else 0.0)
    vy = vx.copy()
    vz = vx.copy()
    rdot = np.zeros(nBubs)

    if _args.perturb:
        amp = _args.perturb_amp
        pos_ss, rad_ss, rdot_ss = np.random.SeedSequence(_args.perturb_seed).spawn(3)
        dpos = np.random.default_rng(pos_ss).uniform(-amp, amp, size=(nBubs, 3))
        x_pos = x_pos + dpos[:, 0]
        y_pos = y_pos + dpos[:, 1]
        z_pos = z_pos + dpos[:, 2]
        R = R + np.random.default_rng(rad_ss).uniform(-amp, amp, size=nBubs)
        rdot = rdot + np.random.default_rng(rdot_ss).uniform(-amp, amp, size=nBubs)

    print(f"lag_bubbles.dat: nBubs={nBubs} perturb={_args.perturb} amp={_args.perturb_amp:.1e}", file=sys.stderr)
    fmt = "\t".join(["%.17e"] * 8) + "\n"
    input_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "input")
    os.makedirs(input_dir, exist_ok=True)
    with open(os.path.join(input_dir, "lag_bubbles.dat"), "w") as f:
        for i in range(nBubs):
            f.write(fmt % (x_pos[i], y_pos[i], z_pos[i], vx[i], vy[i], vz[i], R[i], rdot[i]))


if not _args.no_bubbles:
    write_lag_bubbles_file()

print(json.dumps(data, indent=4))
