#!/usr/bin/env python3
"""Compare per-particle trajectories of two runs from lag_bubble_evol files.

WARNING: This file was generated by Claude Code

Reads D/lag_bubble_evol_<rank>.dat from both run directories (any rank
count -- rows are joined on (time, particleID)), then reports the divergence
between runs over time: max/mean |dpos|, |dR|, |drdot| across particles, and a
log-linear fit of the growth rate of max|dpos| (an e-folding rate to compare
against the chaos baseline).

    python3 compare_particles.py out_A out_B [--plot out.png] [--label-a A]
"""

import argparse
from pathlib import Path

import numpy as np

COLS = ("time", "id", "x", "y", "z", "mv", "cv", "radius", "rdot", "pcore")


def load_run(run_dir: Path) -> dict:
    """-> {(time_key, id): (x, y, z, R, rdot)}; later rows win (re-writes after
    rank transfer or restart overwrite earlier ones)."""
    files = sorted((run_dir / "D").glob("lag_bubble_evol_*.dat"))
    if not files:
        raise SystemExit(f"no lag_bubble_evol files under {run_dir}/D")
    rows = {}
    for f in files:
        with f.open() as fh:
            for line in fh:
                parts = line.split()
                if not parts or not parts[0][0].isdigit() and parts[0][0] not in "+-.":
                    continue  # header
                try:
                    vals = [float(v) for v in parts]
                except ValueError:
                    continue
                t_key = round(vals[0], 10)
                pid = int(vals[1])
                rows[(t_key, pid)] = (vals[2], vals[3], vals[4], vals[7], vals[8])
    return rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("run_a")
    ap.add_argument("run_b")
    ap.add_argument("--plot", default=None)
    ap.add_argument("--label-a", default=None)
    ap.add_argument("--label-b", default=None)
    args = ap.parse_args()

    rows_a = load_run(Path(args.run_a))
    rows_b = load_run(Path(args.run_b))
    common = sorted(set(rows_a) & set(rows_b))
    if not common:
        raise SystemExit("no common (time, particle) samples")

    times = sorted({k[0] for k in common})
    print(f"matched samples: {len(common)} ({len(times)} times)")

    max_dpos, mean_dpos, max_dR, max_drdot = [], [], [], []
    for t in times:
        keys = [k for k in common if k[0] == t]
        a = np.array([rows_a[k] for k in keys])
        b = np.array([rows_b[k] for k in keys])
        dpos = np.linalg.norm(b[:, :3] - a[:, :3], axis=1)
        max_dpos.append(dpos.max())
        mean_dpos.append(dpos.mean())
        max_dR.append(np.abs(b[:, 3] - a[:, 3]).max())
        max_drdot.append(np.abs(b[:, 4] - a[:, 4]).max())

    times = np.array(times)
    max_dpos = np.array(max_dpos)
    max_dR = np.array(max_dR)
    max_drdot = np.array(max_drdot)

    print(f"{'time':>12s} {'max|dpos|':>12s} {'mean|dpos|':>12s} {'max|dR|':>12s} {'max|drdot|':>12s}")
    stride = max(1, len(times) // 25)
    for i in range(0, len(times), stride):
        print(f"{times[i]:12.4f} {max_dpos[i]:12.4e} {mean_dpos[i]:12.4e} " f"{max_dR[i]:12.4e} {max_drdot[i]:12.4e}")

    print(f"\nfinal max|dpos| = {max_dpos[-1]:.4e}   final max|dR| = {max_dR[-1]:.4e}")
    if np.all(max_dpos == 0) and np.all(max_dR == 0) and np.all(max_drdot == 0):
        print("VERDICT: particle trajectories IDENTICAL")
        return

    # e-folding rate of max|dpos| where positive (log-linear least squares)
    mask = (max_dpos > 0) & (times > 0)
    if mask.sum() >= 3:
        rate = np.polyfit(times[mask], np.log(max_dpos[mask]), 1)[0]
        print(f"growth rate of max|dpos|: {rate:.4e} per unit time " f"(e-folding time {1.0/rate if rate > 0 else float('inf'):.4f})")
    onset = times[np.argmax(max_dpos > 0)] if np.any(max_dpos > 0) else None
    first = max_dpos[max_dpos > 0][0] if np.any(max_dpos > 0) else 0.0
    print(f"first nonzero |dpos|: {first:.4e} at t={onset}")

    if args.plot:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        fig, ax = plt.subplots(figsize=(8, 5))
        for series, label in ((max_dpos, "max |Δpos|"), (max_dR, "max |ΔR|"), (max_drdot, "max |Δrdot|")):
            s = np.where(series > 0, series, np.nan)
            ax.plot(times, s, marker="o", ms=3, label=label)
        ax.set_yscale("log")
        ax.set_xlabel("time")
        ax.set_ylabel("divergence")
        la = args.label_a or Path(args.run_a).name
        lb = args.label_b or Path(args.run_b).name
        ax.set_title(f"{la} vs {lb}")
        ax.grid(True, alpha=0.3, which="both")
        ax.legend()
        fig.tight_layout()
        fig.savefig(args.plot, dpi=150)
        print(f"wrote {args.plot}")


if __name__ == "__main__":
    main()
