#!/usr/bin/env python3
"""Compare the conserved-field restart snapshots of two runs.

WARNING: This file was generated by Claude Code

Parallel-IO restart files (lustre_<step>.dat) are raw doubles in a global
Fortran-ordered layout, one block per field, so two runs of the same grid are
directly comparable regardless of rank count -- including bitwise.

    python3 compare_fields.py out_A out_B [--cells 48] [--quiet]

Prints one line per common step: count of differing values, max |abs diff|,
max |rel diff|, and the (field, i, j, k) of the worst cell. Exits 0 if all
common steps are bitwise identical, 1 otherwise (usable as a determinism
check).
"""

import argparse
import re
import sys
from pathlib import Path

import numpy as np

STEP_RE = re.compile(r"lustre_(\d+)\.dat$")


def snapshot_steps(run_dir: Path) -> dict:
    d = run_dir / "restart_data"
    if not d.is_dir():
        raise SystemExit(f"missing directory: {d}")
    out = {}
    for f in d.iterdir():
        m = STEP_RE.match(f.name)
        if m:
            out[int(m.group(1))] = f
    if not out:
        raise SystemExit(f"no lustre_<step>.dat files in {d}")
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("run_a")
    ap.add_argument("run_b")
    ap.add_argument("--cells", type=int, default=50, help="cells per direction (cubic grid)")
    ap.add_argument("--quiet", action="store_true", help="only print the summary verdict")
    args = ap.parse_args()

    steps_a = snapshot_steps(Path(args.run_a))
    steps_b = snapshot_steps(Path(args.run_b))
    common = sorted(set(steps_a) & set(steps_b))
    if not common:
        raise SystemExit("no common steps")

    nc = args.cells
    ncell = nc**3
    all_identical = True
    first_diff_step = None

    for step in common:
        a = np.fromfile(steps_a[step], dtype="<f8")
        b = np.fromfile(steps_b[step], dtype="<f8")
        if a.size != b.size:
            print(f"step {step:>6d}: SIZE MISMATCH {a.size} vs {b.size} doubles")
            all_identical = False
            continue
        diff = np.abs(b - a)
        ndiff = int(np.count_nonzero(diff))
        if ndiff == 0:
            if not args.quiet:
                print(f"step {step:>6d}: bitwise identical ({a.size} doubles)")
            continue
        all_identical = False
        if first_diff_step is None:
            first_diff_step = step
        denom = np.where(np.abs(a) > 0, np.abs(a), 1.0)
        rel = diff / denom
        worst = int(np.argmax(diff))
        loc = ""
        if a.size % ncell == 0:
            nfields = a.size // ncell
            f_idx, cell = divmod(worst, ncell)
            i, j, k = np.unravel_index(cell, (nc, nc, nc), order="F")
            loc = f"  worst: field {f_idx}/{nfields} cell ({i},{j},{k})"
        if not args.quiet:
            print(f"step {step:>6d}: ndiff={ndiff:>9d}  max|d|={diff[worst]:.6e}  " f"max rel={np.max(rel):.6e}{loc}")

    if all_identical:
        print(f"VERDICT: BITWISE IDENTICAL over {len(common)} steps")
        sys.exit(0)
    print(f"VERDICT: differs (first differing step: {first_diff_step})")
    sys.exit(1)


if __name__ == "__main__":
    main()
