#!/usr/bin/env bash
set -euo pipefail

# WARNING: This file was generated by Claude Code
# Phase 1: feature bisection across rank counts.
#
# Four physics cells, each run at 1, 2, and 8 ranks with per-step restart
# snapshots over a short horizon:
#
#   M0  no bubbles                 (pure Eulerian control)
#   M1  static bubbles + two-way   (isolates kernel deposition / beta reduce)
#   M2  moving bubbles + one-way   (isolates interpolation + rank migration)
#   M3  moving bubbles + two-way   (the failing configuration)
#
# The discriminating signal is the FIRST-step field difference vs 1 rank:
#   ~0 or O(1e-16)  -> decomposition changes only round-off (summation order)
#   O(large) at once -> a real decomposition bug in whichever mechanism this
#                       cell adds relative to the last passing cell.

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STEPS=20
BASE=(--steps "$STEPS" --save-every 1)

declare -A CELLS=(
    [M0]="--no-bubbles 1"
    [M1]="--vel-model 0 --solver-approach 2"
    [M2]="--vel-model 2 --solver-approach 1"
    [M3]="--vel-model 2 --solver-approach 2"
)

RANKS=(1 2 8)

for cell in M0 M1 M2 M3; do
    read -r -a cell_flags <<<"${CELLS[$cell]}"
    for nr in "${RANKS[@]}"; do
        "$HERE/run_case.sh" "out_p1_${cell}_${nr}rank" "$nr" "${BASE[@]}" "${cell_flags[@]}" \
            2>&1 | tee "$HERE/run_p1_${cell}_${nr}rank.out"
    done
done

echo
echo "################ PHASE 1 SUMMARY ################"
for cell in M0 M1 M2 M3; do
    for nr in 2 8; do
        echo
        echo "=== $cell : 1 rank vs $nr ranks (fields) ==="
        python3 "$HERE/compare_fields.py" "$HERE/out_p1_${cell}_1rank" "$HERE/out_p1_${cell}_${nr}rank" || true
        if [ "$cell" != "M0" ]; then
            echo "--- $cell : 1 rank vs $nr ranks (particles) ---"
            python3 "$HERE/compare_particles.py" "$HERE/out_p1_${cell}_1rank" "$HERE/out_p1_${cell}_${nr}rank" | tail -6 || true
        fi
    done
done
echo "phase 1 done."
