#!/usr/bin/env bash
set -euo pipefail

# WARNING: This file was generated by Claude Code
# Phase 3: single-bubble boundary forensics (run if Phase 1 shows first-step
# O(large) field differences for M1 or M3).
#
# One bubble, two placements, compared 1 rank vs 2 ranks:
#   straddle  bubble ON the 2-rank subdomain boundary plane -> its smearing
#             kernel spans both ranks from step 0 (kernel truncation / beta
#             buffer reduce bugs show up immediately in the deposited field)
#   interior  same bubble shifted well inside one subdomain (control: kernel
#             never touches the boundary)
# plus a migration test: bubble starts just left of the boundary moving right
# with the background flow, so it crosses ranks mid-run (ownership handoff).
#
# Determine the 2-rank split plane first (check which coordinate splits by
# looking at out_p1_M3_2rank particle ownership, or just try x=0); override
# with BX/BY/BZ env vars if the decomposition splits another axis.

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STEPS=${STEPS:-100}
BASE=(--vel-model 2 --solver-approach 2 --single-bubble 1 --steps "$STEPS" --save-every 5)

BX=${BX:-0.0} # boundary plane position on the split axis
DX=0.04       # one cell

declare -A PLACEMENTS=(
    [straddle]="--bub-x $BX --bub-y 0.0 --bub-z 0.0"
    [interior]="--bub-x 0.5 --bub-y 0.0 --bub-z 0.0"
    [migrate]="--bub-x $(python3 -c "print(${BX} - 2*${DX})") --bub-y 0.0 --bub-z 0.0 --bub-vel 0.05"
)

for place in straddle interior migrate; do
    read -r -a pflags <<<"${PLACEMENTS[$place]}"
    for nr in 1 2; do
        "$HERE/run_case.sh" "out_p3_${place}_${nr}rank" "$nr" "${BASE[@]}" "${pflags[@]}" \
            2>&1 | tee "$HERE/run_p3_${place}_${nr}rank.out"
    done
done

echo
echo "################ PHASE 3 SUMMARY ################"
for place in straddle interior migrate; do
    echo
    echo "=== $place : 1 rank vs 2 ranks (fields) ==="
    python3 "$HERE/compare_fields.py" "$HERE/out_p3_${place}_1rank" "$HERE/out_p3_${place}_2rank" || true
    echo "--- $place : particles ---"
    python3 "$HERE/compare_particles.py" "$HERE/out_p3_${place}_1rank" "$HERE/out_p3_${place}_2rank" | tail -6 || true
done
echo "phase 3 done."
