#!/usr/bin/env bash
set -euo pipefail

# WARNING: This file was generated by Claude Code
# Phase 2: chaos baseline vs rank divergence, moving + two-way (M3).
#
# Three runs over a longer horizon:
#   A  8 ranks, unperturbed          (reference)
#   B  8 ranks, 1e-14 IC perturbed   (chaos baseline: A vs B isolates the
#                                     intrinsic amplification of a machine-
#                                     precision difference, same decomposition)
#   C  1 rank,  unperturbed          (A vs C isolates decomposition effects)
#
# If growth-rate(A vs C) == growth-rate(A vs B) and A-vs-C starts at machine
# precision, the rank-count discrepancy is round-off seeded + chaotically
# amplified, not a coding bug. A-vs-C growing faster, or starting above
# ~1e-12, indicates a real decomposition bug.

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STEPS=${STEPS:-500}
SAVE=$((STEPS / 20))
FLAGS=(--vel-model 2 --solver-approach 2 --steps "$STEPS" --save-every "$SAVE")

"$HERE/run_case.sh" out_p2_ref8 8 "${FLAGS[@]}" 2>&1 | tee "$HERE/run_p2_ref8.out"
"$HERE/run_case.sh" out_p2_pert8 8 "${FLAGS[@]}" --perturb 1 2>&1 | tee "$HERE/run_p2_pert8.out"
"$HERE/run_case.sh" out_p2_ref1 1 "${FLAGS[@]}" 2>&1 | tee "$HERE/run_p2_ref1.out"

echo
echo "################ PHASE 2 SUMMARY ################"
echo
echo "=== chaos baseline: 8rank ref vs 8rank perturbed (1e-14 IC) ==="
python3 "$HERE/compare_particles.py" "$HERE/out_p2_ref8" "$HERE/out_p2_pert8" \
    --plot "$HERE/p2_chaos_baseline.png" --label-a ref8 --label-b pert8
echo
echo "=== rank divergence: 8rank ref vs 1rank ref ==="
python3 "$HERE/compare_particles.py" "$HERE/out_p2_ref8" "$HERE/out_p2_ref1" \
    --plot "$HERE/p2_rank_divergence.png" --label-a ref8 --label-b ref1
echo
echo "=== rank divergence: fields ==="
python3 "$HERE/compare_fields.py" "$HERE/out_p2_ref8" "$HERE/out_p2_ref1" || true
echo "phase 2 done."
