#!/usr/bin/env bash
set -euo pipefail

# WARNING: This file was generated by Claude Code
# Run one matrix cell and snapshot its native outputs.
#
#   ./run_case.sh <outdir> <nranks> [case flags...]
#
# Outputs land in <outdir>/ relative to this directory:
#   restart_data/lustre_<step>.dat   full conserved-field snapshots (parallel IO,
#                                    global layout => directly comparable across
#                                    rank counts with compare_fields.py)
#   D/lag_bubble_evol_<rank>.dat     per-particle time series (compare_particles.py)
#   lag_bubbles.dat                  the exact IC fed to the run
#   meta.txt                         rank count + flags
#
# GPU=1 ./run_case.sh ...  runs the simulation on GPU (requires --gpu build).

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/../.." && pwd)"
CASE_REL="examples/3D_lagrange_coupling_matrix/case_matrix.py"

OUT="$HERE/$1"
N="$2"
shift 2

# NVEnv.sh reads $1 as an SDK version (pass it explicitly so this script's
# args don't leak in) and touches unset vars (relax -u around it).
set +u
source /fastscratch/bwilfong3/NVEnv.sh 25.11
set -u

# Pin the configuration explicitly: mfc.sh otherwise reuses the last-built
# config (lock), which silently switched a CPU campaign onto the GPU build.
GPU_FLAG=(--no-gpu)
if [ "${GPU:-0}" = "1" ]; then
    GPU_FLAG=(--gpu)
fi

rm -rf "$HERE/restart_data" "$HERE/D" "$OUT"

cd "$REPO_ROOT"
./mfc.sh run "$CASE_REL" -n "$N" -t pre_process simulation \
    --no-debug --no-reldebug --mpi "${GPU_FLAG[@]}" -- "$@"

mkdir -p "$OUT"
mv "$HERE/restart_data" "$OUT/restart_data"
[ -d "$HERE/D" ] && mv "$HERE/D" "$OUT/D"
[ -f "$HERE/input/lag_bubbles.dat" ] && cp "$HERE/input/lag_bubbles.dat" "$OUT/"
echo "nranks=$N gpu=${GPU:-0} flags=$*" > "$OUT/meta.txt"
echo "saved $OUT"
