#!/usr/bin/env bash
set -euo pipefail

# WARNING: This file was generated by Claude Code
# Phase 0: determinism audit. Run the full moving+two-way configuration twice
# with IDENTICAL inputs and rank counts, and demand bitwise-identical output.
# If a same-config pair differs, every cross-rank-count comparison is
# confounded by run-to-run noise (e.g. GPU atomics) and must be interpreted
# accordingly.
#
#   ./run_phase0_determinism.sh          # CPU: 1-rank pair + 8-rank pair
#   GPU=1 ./run_phase0_determinism.sh    # add GPU 1-rank + 4-rank pairs

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STEPS=20
FLAGS=(--vel-model 2 --solver-approach 2 --steps "$STEPS" --save-every 5)

run_pair() { # <tag> <nranks> <gpu 0|1>
    local tag=$1 nr=$2 gpu=$3
    for rep in a b; do
        GPU=$gpu "$HERE/run_case.sh" "out_p0_${tag}_${rep}" "$nr" "${FLAGS[@]}" \
            2>&1 | tee "$HERE/run_p0_${tag}_${rep}.out"
    done
    echo
    echo "=== determinism ${tag}: fields ==="
    python3 "$HERE/compare_fields.py" "$HERE/out_p0_${tag}_a" "$HERE/out_p0_${tag}_b" || true
    echo "=== determinism ${tag}: particles ==="
    python3 "$HERE/compare_particles.py" "$HERE/out_p0_${tag}_a" "$HERE/out_p0_${tag}_b" | tail -5 || true
    echo
}

run_pair cpu1 1 0
run_pair cpu8 8 0

if [ "${GPU:-0}" = "1" ]; then
    run_pair gpu1 1 1
    run_pair gpu4 4 1
fi

echo "phase 0 done."
