#!/usr/bin/env bash
set -euo pipefail

# WARNING: This file was generated by Claude Code
# Run the complete campaign from a clean tree: builds, phases 0-3, and the
# Kahan probe. Sequential by design -- all runs share this case directory.
#
#   ./run_all.sh          # everything, incl. GPU determinism pairs (~1.5-2 h)
#   GPU=0 ./run_all.sh    # CPU only (no GPU build or GPU pairs)
#
# Logs land in phase{0,1,2,3}.log + kahan.log; outputs in out_*/ (~20 GB).
# Expected results: FINDINGS.md.

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/../.." && pwd)"

WITH_GPU="${GPU:-1}"
# The GPU env var switches run_case.sh onto the GPU build; keep the CPU
# phases pinned to CPU regardless of what the caller exported.
export GPU=0

set +u
source /fastscratch/bwilfong3/NVEnv.sh 25.11
set -u

echo "== building (cpu+mpi$([ "$WITH_GPU" = "1" ] && echo ", gpu")) =="
cd "$REPO_ROOT"
./mfc.sh build -t pre_process simulation --no-gpu -j 32
if [ "$WITH_GPU" = "1" ]; then
    ./mfc.sh build -t pre_process simulation --gpu -j 32
fi
cd "$HERE"

echo "== phase 1: feature bisection (M0-M3 x 1/2/8 ranks) =="
./run_phase1_matrix.sh 2>&1 | tee phase1.log

echo "== phase 0: determinism audits =="
GPU="$WITH_GPU" ./run_phase0_determinism.sh 2>&1 | tee phase0.log

echo "== phase 2: chaos baseline vs rank divergence (longest phase) =="
./run_phase2_chaos.sh 2>&1 | tee phase2.log

echo "== phase 3: single-bubble boundary forensics =="
./run_phase3_boundary.sh 2>&1 | tee phase3.log

echo "== kahan probe: does kahan_summation remove the rank seed? =="
{
    ./run_case.sh out_kahan_1rank 1 --vel-model 0 --solver-approach 2 --kahan 1 --steps 20 --save-every 1
    ./run_case.sh out_kahan_2rank 2 --vel-model 0 --solver-approach 2 --kahan 1 --steps 20 --save-every 1
    python3 compare_fields.py out_kahan_1rank out_kahan_2rank || true
} 2>&1 | tee kahan.log

echo
echo "run_all done. Verdicts:"
grep -h "VERDICT" phase0.log phase1.log phase3.log kahan.log | sort | uniq -c
echo "Growth rates (phase 2):"
grep -h "growth rate" phase2.log
echo "Compare against FINDINGS.md."
