name: "Update contributors"
on:
  push:
    branches: [ master ]
jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Run all-contributors
        run: npx all-contributors-cli generate
      - name: Commit updated contributors
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update contributors" || echo "No changes to commit"
          git push
