name: Cleanness

on: [push, pull_request, workflow_dispatch]

jobs:
  file-changes:
    name: Detect File Changes
    runs-on: 'ubuntu-latest'
    outputs: 
      checkall: ${{ steps.changes.outputs.checkall }}
    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Detect Changes
        uses: dorny/paths-filter@v3
        id: changes
        with: 
          filters: ".github/file-filter.yml"

  run:
    name: Code Cleanness Test
    if: needs.file-changes.outputs.checkall == 'true'
    needs: file-changes
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkouts
        uses: actions/checkout@v4

      - name: Setup Ubuntu
        run: |
            sudo apt update -y
            sudo apt install -y tar wget make cmake gcc g++ python3 python3-dev "openmpi-*" libopenmpi-dev
            
      
      - name: Build
        run: |
            /bin/bash mfc.sh build -j $(nproc) --debug > out.txt 2>&1 
      
      - name: Unused Variables
        run: |
            grep -F 'Wunused-variable' out.txt -B 4
      
      - name: Unused Dummy Arguments
        run: |
            grep -F 'Wunused-dummy-argument' out.txt -B 4

      - name: Unused Value
        run: |
            grep -F 'Wunused-value' out.txt -B 4
    
      - name: Maybe Uninitialized Variables
        run: |
            grep -F 'Wmaybe-uninitialized' out.txt -B 4

      - name: Everything
        run: |
            grep '\-W' out.txt -B 4

      - name: Summary
        run: |
            echo "Unused Variable Count:" 
            grep -c -F 'Wunused-variable' out.txt -B 4
            echo "Unused Dummy Arguments Count: "
            grep -c -F 'Wunused-dummy-argument' out.txt -B 4
            echo "Unused Value Count: "
            grep -c -F 'Wunused-value' out.txt -B 4
            echo "Maybe Uninitialized Variables Count: "
            grep -c -F 'Wmaybe-uninitialized' out.txt -B 4
            echo "Everything"
            grep -c '\-W' out.txt -B 4