name: Build Singularity Images

on:
  push:

jobs:
  Build-singularity-images:
    name: Build Singularity Images
    runs-on: ubuntu-latest
    steps:
      - name: Clone - PR
        uses: actions/checkout@v4
        with:
          path: pr
      - name: Set up Singularity
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:apptainer/ppa
          sudo apt-get update
          sudo apt-get install -y apptainer
          whoami
          sudo apptainer config fakeroot --enable $(whoami)          
      - name: Build Singularity Images
        run: |
          echo "Building Singularity CPU Image"
          (cd pr/.github/workflows/images && sudo apptainer build pr/.github/workflows/images/mfc_cpu.sif Singularity.cpu)
          apptainer run --fakeroot pr/.github/workflows/images/mfc_cpu.sif test -a --no-build --no-mpi
      - name: Upload images as artifacts
        uses: actions/upload-artifact@v4
        if:   always()
        with:
          name: singularity-images
          path: |
            pr/.github/workflows/images/mfc_cpu.sif
