name: Build Singularity Images

on:
  push:

jobs:
  Build-singularity-images:
    name: Build Singularity Images
    runs-on: ubuntu-latest
    steps:
      - name: Clone - PR
        uses: actions/checkout@v4
        with:
          path: pr


      - name: Build & Store Images
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common openssh-client
          sudo add-apt-repository -y ppa:apptainer/ppa
          sudo apt-get install -y apptainer
          sudo apptainer config fakeroot --enable $(whoami)
          
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" >~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ap40.uw.osg-htc.org >> ~/.ssh/known_hosts

          (cd pr/.github/workflows/images && sudo apptainer build mfc_cpu.sif Singularity.cpu)
          scp pr/.github/workflows/images/mfc_cpu.sif ${{secrets.SSH_USER}}:MFC/mfc_cpu.sif
          ssh ${{secrets.SSH_USER}} "mv /home/mohammed.al-mahrouqi/MFC/mfc_cpu.sif /ospool/ap40/data/mohammed.al-mahrouqi"
          rm -rf pr/.github/workflows/images/mfc_cpu.sif
          rm -rf ~/.apptainer
          sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/share/boost /usr/lib/jvm
          sudo apt-get clean


          # (cd pr/.github/workflows/images && sudo apptainer build mfc_cpu_bench.sif Singularity.cpu_bench)
          # scp pr/.github/workflows/images/mfc_cpu_bench.sif ${{secrets.SSH_USER}}:MFC/mfc_cpu_bench.sif
          # ssh ${{secrets.SSH_USER}} "mv /home/mohammed.al-mahrouqi/MFC/mfc_cpu_bench.sif /ospool/ap40/data/mohammed.al-mahrouqi"
          # rm -rf pr/.github/workflows/images/mfc_cpu_bench.sif
          # rm -rf ~/.apptainer
          # sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/share/boost /usr/lib/jvm
          # sudo apt-get clean


          (cd pr/.github/workflows/images && sudo apptainer build mfc_gpu.sif Singularity.gpu)
          scp pr/.github/workflows/images/mfc_gpu.sif ${{secrets.SSH_USER}}:MFC/mfc_gpu.sif
          ssh ${{secrets.SSH_USER}} "mv /home/mohammed.al-mahrouqi/MFC/mfc_gpu.sif /ospool/ap40/data/mohammed.al-mahrouqi"
          rm -rf pr/.github/workflows/images/mfc_gpu.sif
          rm -rf ~/.apptainer
          sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/share/boost /usr/lib/jvm
          sudo apt-get clean


          # (cd pr/.github/workflows/images && sudo apptainer build mfc_gpu_bench.sif Singularity.gpu_bench)
          # scp pr/.github/workflows/images/mfc_gpu_bench.sif ${{secrets.SSH_USER}}:MFC/mfc_gpu_bench.sif
          # ssh ${{secrets.SSH_USER}} "mv /home/mohammed.al-mahrouqi/MFC/mfc_gpu_bench.sif /ospool/ap40/data/mohammed.al-mahrouqi"
          # rm -rf pr/.github/workflows/images/mfc_gpu_bench.sif
          # rm -rf ~/.apptainer
          # sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/share/boost /usr/lib/jvm
          # sudo apt-get clean

      
      - name: Test Images
        run: |
          scp pr/.github/workflows/images/*.sub ${{secrets.SSH_USER}}:MFC/

          ssh ${{secrets.SSH_USER}} "
            condor_submit MFC/mfc_cpu.sub
            condor_submit MFC/mfc_cpu_bench.sub
            condor_submit MFC/mfc_gpu.sub
            condor_submit MFC/mfc_gpu_bench.sub

            condor_wait logfile
          "

      - name: Migrate Images to ODSF
        run: |
          scp -r ${{secrets.SSH_USER}}:/ospool/ap40/data/mohammed.al-mahrouqi/* pr/.github/workflows/images/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        if:   always()
        with:
          name: singularity-images
          path: |
            pr/.github/workflows/images/*