name: Build Singularity Images

on:
  push:

jobs:
  Build-singularity-images:
    name: Build Singularity Images
    runs-on: ubuntu-latest
    steps:
      - name: Clone - PR
        uses: actions/checkout@v4
        with:
          path: pr

      - name: Build & Store Images
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ap40.uw.osg-htc.org >> ~/.ssh/known_hosts

          scp -r pr/.* pr/* ${{secrets.SSH_USER}}:MFC/ 2>/dev/null || true

          ssh ${{secrets.SSH_USER}} "
            cd MFC/.github/workflows/images
            rm -rf *.sif *.log *.err *.out
            apptainer config fakeroot --enable $(whoami)
            apptainer build mfc_cpu.sif Singularity.cpu > singularity.cpu.log
            mv /home/mohammed.al-mahrouqi/MFC/.github/workflows/images/mfc_cpu.sif /ospool/ap40/data/mohammed.al-mahrouqi
            apptainer build mfc_cpu_bench.sif Singularity.cpu_bench > singularity.cpu_bench.log
            mv /home/mohammed.al-mahrouqi/MFC/.github/workflows/images/mfc_cpu_bench.sif /ospool/ap40/data/mohammed.al-mahrouqi
            apptainer build mfc_gpu.sif Singularity.gpu > singularity.gpu.log
            mv /home/mohammed.al-mahrouqi/MFC/.github/workflows/images/mfc_gpu.sif /ospool/ap40/data/mohammed.al-mahrouqi
            apptainer build mfc_gpu_bench.sif Singularity.gpu_bench > singularity.gpu_bench.log
            mv /home/mohammed.al-mahrouqi/MFC/.github/workflows/images/mfc_gpu_bench.sif /ospool/ap40/data/mohammed.al-mahrouqi
            "
      
      - name: Test Images
        run: |
          ssh ${{secrets.SSH_USER}} "
            condor_submit MFC/mfc_cpu.sub
            condor_submit MFC/mfc_cpu_bench.sub
            condor_submit MFC/mfc_gpu.sub
            condor_submit MFC/mfc_gpu_bench.sub

            condor_wait logfile
          "

      - name: Migrate Images to ODSF
        run: |
          scp -r ${{secrets.SSH_USER}}:/ospool/ap40/data/mohammed.al-mahrouqi/* pr/.github/workflows/images/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        if:   always()
        with:
          name: singularity-images
          path: |
            pr/.github/workflows/images/*