name: Build Singularity Images

on:
  push:

jobs:
  file-changes:
    name: Detect File Changes
    runs-on: 'ubuntu-latest'
    outputs: 
      checkall: ${{ steps.changes.outputs.checkall }}
    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Detect Changes
        uses: dorny/paths-filter@v3
        id: changes
        with: 
          filters: ".github/file-filter.yml"

  build-singularity-images:
    needs: file-changes
    if: needs.file-changes.outputs.checkall == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Clone - PR
        uses: actions/checkout@v4
        with:
          path: pr
      - name: Set up Singularity
        uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3

      - name: Build Singularity Images
        run: |
          echo "Building Singularity CPU Image"
          (cd pr/.github/workflows/images && singularity build mfc_cpu.sif Singularity.cpu)
          echo "Building Singularity GPU Image"
          (cd pr/.github/workflows/images && singularity build mfc_gpu.sif Singularity.gpu)
          echo "Building Singularity CPU Benchmark Image"
          (cd pr/.github/workflows/images && singularity build mfc_cpu_bench.sif Singularity.cpu_bench)
          echo "Building Singularity GPU Benchmark Image"
          (cd pr/.github/workflows/images && singularity build mfc_gpu_bench.sif Singularity.gpu_bench)
        shell: /usr/bin/bash -e {0}
        env:
          SINGULARITY_ROOT: /opt/hostedtoolcache/singularity/3.8.3/x64

      - name: Upload images as artifacts
        uses: actions/upload-artifact@v4
        if:   always()
        with:
          name: singularity-images
          path: |
            pr/.github/workflows/images/mfc_cpu.sif
            pr/.github/workflows/images/mfc_gpu.sif
            pr/.github/workflows/images/mfc_cpu_bench.sif
            pr/.github/workflows/images/mfc_gpu_bench.sif