name: Build Singularity Images

on:
  push:

jobs:
  file-changes:
    name: Detect File Changes
    runs-on: 'ubuntu-latest'
    outputs: 
      checkall: ${{ steps.changes.outputs.checkall }}
    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Detect Changes
        uses: dorny/paths-filter@v3
        id: changes
        with: 
          filters: ".github/file-filter.yml"

  Build-singularity-images:
    name: Build Singularity Images
    needs: file-changes
    if: needs.file-changes.outputs.checkall == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Clone - PR
        uses: actions/checkout@v4
        with:
          path: pr
      - name: Set up Singularity
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:apptainer/ppa
          sudo apt-get update
          sudo apt-get install -y apptainer
          whoami
          sudo apptainer config fakeroot --enable $(whoami)          
      - name: Build Singularity Images
        run: |
          echo "Building Singularity CPU Image"
          (cd pr/.github/workflows/images && sudo apptainer build mfc_cpu.sif Singularity.cpu)
          echo "Building Singularity GPU Image"
          (cd pr/.github/workflows/images && sudo apptainer build mfc_gpu.sif Singularity.gpu)
          echo "Building Singularity CPU Benchmark Image"
          (cd pr/.github/workflows/images && sudo apptainer build mfc_cpu_bench.sif Singularity.cpu_bench)
          echo "Building Singularity GPU Benchmark Image"
          (cd pr/.github/workflows/images && sudo apptainer build mfc_gpu_bench.sif Singularity.gpu_bench)
      - name: Upload images as artifacts
        uses: actions/upload-artifact@v4
        if:   always()
        with:
          name: singularity-images
          path: |
            pr/.github/workflows/images/mfc_cpu.sif
            pr/.github/workflows/images/mfc_gpu.sif
            pr/.github/workflows/images/mfc_cpu_bench.sif
            pr/.github/workflows/images/mfc_gpu_bench.sif