name: Build Singularity Images

on:
  push:

jobs:
  Build-singularity-images:
    name: Build Singularity Images
    runs-on: ubuntu-latest
    steps:
      - name: Clone - PR
        uses: actions/checkout@v4
        with:
          path: pr

      - name: Build & Store Images
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common openssh-client
          sudo add-apt-repository -y ppa:apptainer/ppa
          sudo apt-get install -y apptainer
          sudo apptainer config fakeroot --enable $(whoami)

          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ap40.uw.osg-htc.org >> ~/.ssh/known_hosts

          scp -r pr/.* pr/* ${{secrets.SSH_USER}}:MFC/ 2>/dev/null || true

          ssh ${{secrets.SSH_USER}} "
            cd MFC/.github/workflows/images
            apptainer build mfc_cpu.sif Singularity.cpu > singularity.cpu.log
            apptainer build mfc_cpu_bench.sif Singularity.cpu_bench > singularity.cpu_bench.log
            apptainer build mfc_gpu.sif Singularity.gpu > singularity.gpu.log
            apptainer build mfc_gpu_bench.sif Singularity.gpu_bench > singularity.gpu_bench.log
            "
      
      - name: Test Images
        run: |
          ssh ${{secrets.SSH_USER}} "
            condor_submit MFC/mfc_cpu.sub
            condor_submit MFC/mfc_cpu_bench.sub
            condor_submit MFC/mfc_gpu.sub
            condor_submit MFC/mfc_gpu_bench.sub

            condor_wait logfile
          "

      - name: Upload images as artifacts
        uses: actions/upload-artifact@v4
        if:   always()
        with:
          name: singularity-images
          path: |
            pr/.github/workflows/images/*