name: Build Singularity Images

on:
  push:

jobs:
  file-changes:
    name: Detect File Changes
    runs-on: 'ubuntu-latest'
    outputs: 
      checkall: ${{ steps.changes.outputs.checkall }}
    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Detect Changes
        uses: dorny/paths-filter@v3
        id: changes
        with: 
          filters: ".github/file-filter.yml"

  build-singularity-images:
    needs: file-changes
    if: needs.file-changes.outputs.checkall == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Singularity
        uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3

      - name: Build CPU image
        run: |
          (cd .github/workflows/images && singularity build mfc_cpu.sif Singularity.cpu)

      - name: Build GPU image
        run: |
          (cd .github/workflows/images && singularity build mfc_gpu.sif Singularity.gpu)

      - name: Build CPU Benchmark image
        run: |
          (cd .github/workflows/images && singularity build mfc_cpu_bench.sif Singularity.cpu_bench)

      - name: Build GPU Benchmark image
        run: |
          (cd .github/workflows/images && singularity build mfc_gpu_bench.sif Singularity.gpu_bench)

      - name: Upload images as artifacts
        uses: actions/upload-artifact@v4
        if:   always()
        with:
          name: singularity-images
          path: |
            mfc_cpu.sif
            mfc_gpu.sif
            mfc_cpu_bench.sif
            mfc_gpu_bench.sif