name: Build Singularity Images

on:
  push:

jobs:
  build-singularity-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Singularity
        uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3

      - name: Build CPU image
        run: |
          singularity build .github/workflows/images/mfc_cpu.sif .github/workflows/images/Singularity.cpu

      - name: Build GPU image
        run: |
          singularity build .github/workflows/images/mfc_gpu.sif .github/workflows/images/Singularity.gpu

      - name: Build CPU Benchmark image
        run: |
          singularity build .github/workflows/images/mfc_cpu_bench.sif .github/workflows/images/Singularity.cpu_bench

      - name: Build GPU Benchmark image
        run: |
          singularity build .github/workflows/images/mfc_gpu_bench.sif .github/workflows/images/Singularity.gpu_bench

      - name: Upload images as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: singularity-images
          path: |
            .github/workflows/images/mfc_cpu.sif
            .github/workflows/images/mfc_gpu.sif
            .github/workflows/images/mfc_cpu_bench.sif
            .github/workflows/images/mfc_gpu_bench.sif