name: Build Singularity Images

on:
  push:

jobs:
  Build-singularity-images:
    name: Build Singularity Images
    runs-on: ubuntu-latest
    steps:
      - name: Clone - PR
        uses: actions/checkout@v4
        with:
          path: pr

      - name: Set up & Build Images
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common openssh-client
          sudo add-apt-repository -y ppa:apptainer/ppa
          sudo apt-get install -y apptainer
          sudo apptainer config fakeroot --enable $(whoami)
          (cd pr/.github/workflows/images && sudo apptainer build mfc_cpu.sif Singularity.cpu)

      - name: Test and Store Images
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" >~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ap40.uw.osg-htc.org >> ~/.ssh/known_hosts
          scp pr/.github/workflows/images/mfc_cpu.sif ${{secrets.SSH_USER}}:MFC/mfc_cpu.sif
          ssh ${{secrets.SSH_USER}} "
            apptainer run --fakeroot MFC/mfc_cpu.sif test -a --no-build --no-mpi
          "

      - name: Upload images as artifacts
        uses: actions/upload-artifact@v4
        if:   always()
        with:
          name: singularity-images
          path: |
            pr/.github/workflows/images/*