name: Continuous Benchmarking

on:
  pull_request:

permissions:
  contents: write
  deployments: write
  pages: write
  id-token: write

jobs:
  self:
    name: "Continuous Benchmarking"
    runs-on: ubuntu-latest
    steps:
      - name: Clone - PR
        uses: actions/checkout@v4
        with:
          path: pr

      - name: Setup
        run: | 
          sudo apt update -y
          sudo apt install -y cmake gcc g++ python3 python3-dev hdf5-tools \
                    libfftw3-dev libhdf5-dev openmpi-bin libopenmpi-dev
          export TOKEN=$(gh auth token)
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          yq --version

      - name: Run Fortran Benchmark
        run: |
          (cd pr     && ./mfc.sh bench -o bench.yaml)
          find pr/ -maxdepth 1 -name "*.yaml" -exec sh -c 'yq eval -o=json "$1" > "${1%.yaml}.json"' _ {} \;