name: Check Line Counts
on: [push]

jobs:
  sz:
    name: Core MFC Line Difference
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from PR branch
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}
          path: pr
        # the base default to MFC master and cannot be other fork branch for security purpose
      - name: Checkout code from MFC master
        uses: actions/checkout@v4
        with:
          path: base

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Count Lines
        run: |
          BASE="$GITHUB_WORKSPACE/base"
          PR="$GITHUB_WORKSPACE/pr"
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          cd $BASE
          ./mfc.sh count
          cd $PR
          ./mfc.sh count

          # echo "test_result<<$EOF" >> "$GITHUB_ENV"
          # cd $BASE && ./mfc.sh count >> "$GITHUB_ENV"
          # echo "this is only a test" >> "GITHUB_ENV"
          # cd $PR && ./mfc.sh count >> "$GITHUB_ENV"
          # echo "this is only a test" >> "GITHUB_ENV"
          # echo "$EOF" >> "$GITHUB_ENV"
      # - uses: marocchino/sticky-pull-request-comment@v2
      #   with:
      #     append: true
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     ignore_empty: false
      #     skip_unchanged: false
      #     recreate: true
      #     message: |
      #       Test with ${{ github.sha }}.
      #       ```
      #       ${{ env.test_result }}
      #       ```

