name: Containerization

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag to containerize'
        required: true

concurrency:
  group: Containerization
  cancel-in-progress: false

jobs:
  Container:
    strategy:
      matrix:
        config:
            - { name: 'cpu', runner: 'ubuntu-22.04',         base_image: 'ubuntu:22.04' }
            - { name: 'gpu', runner: 'ubuntu-22.04',         base_image: 'nvcr.io/nvidia/nvhpc:23.11-devel-cuda_multi-ubuntu22.04' }
            - { name: 'gpu', runner: 'ubuntu-22.04-arm',     base_image: 'nvcr.io/nvidia/nvhpc:23.11-devel-cuda_multi-ubuntu22.04' }
    runs-on: ${{ matrix.config.runner }}
    outputs:
      tag: ${{ steps.clone.outputs.tag }}
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Clone
        id: clone
        run: |
          TAG="${{ github.event.inputs.tag || github.ref_name }}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "TAG=$TAG" >> $GITHUB_ENV
          git clone --branch "$TAG" --depth 1 https://github.com/MFlowCode/MFC.git mfc

      - name: Stage
        run: |
          sudo fallocate -l 8G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo mkdir -p /home/runner/tmp
          export TMPDIR=/home/runner/tmp
          free -h
          sudo mkdir -p /mnt/share
          sudo chmod 777 /mnt/share
          cp -r mfc/* /mnt/share/
          cp -r mfc/.git /mnt/share/.git
          cp mfc/.github/Dockerfile /mnt/share/
          cp mfc/.github/.dockerignore /mnt/share/
          docker buildx create --name mfcbuilder --driver docker-container --use

      - name: Build and push image (cpu)
        if: ${{ matrix.config.name == 'cpu' }}
        uses: docker/build-push-action@v6
        with:
          builder: mfcbuilder
          context: /mnt/share
          file: /mnt/share/Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            BASE_IMAGE=${{ matrix.config.base_image }}
            TARGET=${{ matrix.config.name }}
            CC_COMPILER=${{ 'gcc' }}
            CXX_COMPILER=${{ 'g++' }}
            FC_COMPILER=${{ 'gfortran' }}
            COMPILER_PATH=${{ '/usr/bin' }}
            COMPILER_LD_LIBRARY_PATH=${{ '/usr/lib' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mfc:${{ env.TAG }}-${{ matrix.config.name }}
          push: true

      - name: Build and push image (gpu)
        if: ${{ matrix.config.name == 'gpu' }}
        uses: docker/build-push-action@v5
        with:
          builder: default
          context: /mnt/share
          file: /mnt/share/Dockerfile
          build-args: |
            BASE_IMAGE=${{ matrix.config.base_image }}
            TARGET=${{ matrix.config.name }}
            CC_COMPILER=${{ 'nvc' }}
            CXX_COMPILER=${{ 'nvc++' }}
            FC_COMPILER=${{ 'nvfortran' }}
            COMPILER_PATH=${{ '/opt/nvidia/hpc_sdk/Linux_x86_64/compilers/bin' }}
            COMPILER_LD_LIBRARY_PATH=${{ '/opt/nvidia/hpc_sdk/Linux_x86_64/compilers/lib' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mfc:${{ env.TAG }}-${{ matrix.config.name }}-${{ matrix.config.runner}}
          push: true

  manifests:
    runs-on: ubuntu-latest
    needs: Container
    steps:
      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Create and Push Manifest Lists
        env:
          TAG: ${{ needs.Container.outputs.tag }}
          REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}/mfc
        run: |
          docker buildx imagetools create -t $REGISTRY:latest-cpu $REGISTRY:$TAG-cpu
          docker manifest create $REGISTRY:$TAG-gpu $REGISTRY:$TAG-gpu-ubuntu-22.04 $REGISTRY:$TAG-gpu-ubuntu-22.04-arm
          docker manifest create $REGISTRY:latest-gpu $REGISTRY:$TAG-gpu-ubuntu-22.04 $REGISTRY:$TAG-gpu-ubuntu-22.04-arm
          docker manifest push $REGISTRY:$TAG-gpu
          docker manifest push $REGISTRY:latest-gpu