name: 'Intel Compilers'

on: [push, pull, workflow_dispatch]
    
jobs:
  intel:
    name: intel
    continue-on-error: true
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v4
      
      - name: Setup Ubuntu (Intel)
        run: |
          wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          sudo add-apt-repository -y "deb https://apt.repos.intel.com/oneapi all main"
          echo "Add-apt-repository Complete"
          sudo apt-get update
          sudo apt-get install -y intel-oneapi-compiler-fortran intel-oneapi-mpi intel-oneapi-mpi-devel
          echo "Installed"
          source /opt/intel/oneapi/setvars.sh

      - name: Build
        run:  |
          /bin/bash mfc.sh test --dry-run -j $(nproc) --no-debug --mpi

      - name: Test
        run:  |
          /bin/bash mfc.sh test --max-attempts 3 -j $(nproc) --no-debug --mpi
