name: Pretty

on:
  push:

  pull_request:

  workflow_dispatch:

jobs:
  docs:
    name:    Code formatting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check formatting
      run: |
        ./mfc.sh format -j $(nproc)
        git diff --exit-code
