name: Pretty

on:
  push:

  pull_request:

  workflow_dispatch:

jobs:
  docs:
    name:    Code formatting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Check formatting
      run: |
        ./mfc.sh format
        git diff --exit-code
