#!/usr/bin/env python3
import json
import math

config = {
    # Logistics
    "run_time_info": "T",
    # Computational Domain Parameters
    "x_domain%beg": 0,
    "x_domain%end": 1.0,
    "y_domain%beg": 0,
    "y_domain%end": 1.0,
    "m": 49,
    "n": 49,
    "p": 0,
    "dt": 3.0e-6,
    "t_step_start": 0,
    "t_step_stop": 250,
    "t_step_save": 50,
    # Simulation Algorithm Parameters
    "num_patches": 2,
    "model_eqns": 2,
    "alt_soundspeed": "F",
    "num_fluids": 2,
    # "mpp_lim": "F",
    "mpp_lim": "T",
    "mixture_err": "F",
    "time_stepper": 1,
    "weno_order": 1,
    "weno_eps": 1.0e-20,
    # "mapped_weno": "T",
    "null_weights": "F",
    "mp_weno": "F",
    # "riemann_solver": 2,
    "riemann_solver": 4,
    # "riemann_hypo_ADC": 'T',
    # "ADC_kappa": 1.0,
    "wave_speeds": 1,
    "avg_state": 2,
    # "bc_x%beg": -6,
    # "bc_x%end": -6,
    # "bc_y%beg": -6,
    # "bc_y%end": -6,
    "bc_x%beg": -3,
    "bc_x%end": -3,
    "bc_y%beg": -3,
    "bc_y%end": -3,
    # !!! BC=-6 doesn't work with 1st order upwind !!!
    # Formatted Database Files Structure Parameters
    "format": 1,
    # "format": 2,
    "precision": 2,
    "prim_vars_wrt": "T",
    "rho_wrt": "T",
    "parallel_io": "T",
    # Hypoelasticity
    "hypoelasticity": "T",
    "fd_order": 4,
    # Patch 1 Liquid
    "patch_icpp(1)%geometry": 3,
    "patch_icpp(1)%x_centroid": 0.5,
    "patch_icpp(1)%y_centroid": 0.5,
    "patch_icpp(1)%length_x": 1.0,
    "patch_icpp(1)%length_y": 1.0,
    "patch_icpp(1)%vel(1)": 0.0,
    "patch_icpp(1)%vel(2)": 0.0,
    "patch_icpp(1)%pres": 1e05,
    "patch_icpp(1)%tau_e(1)": 0.0,
    "patch_icpp(1)%alpha_rho(1)": 1000 * (1.0 - 1e-8),
    "patch_icpp(1)%alpha(1)": 1.0 - 1e-8,
    "patch_icpp(1)%alpha_rho(2)": 1000 * 1e-8,
    "patch_icpp(1)%alpha(2)": 1e-8,
    # Patch 1 Solid
    "patch_icpp(2)%alter_patch(1)": "T",
    "patch_icpp(2)%geometry": 2,
    "patch_icpp(2)%x_centroid": 0.6,
    "patch_icpp(2)%y_centroid": 0.5,
    "patch_icpp(2)%radius": 0.1,
    "patch_icpp(2)%vel(1)": 0.0,
    "patch_icpp(2)%vel(2)": 0.0,
    "patch_icpp(2)%pres": 1e05,
    "patch_icpp(2)%tau_e(1)": 0.0,
    "patch_icpp(2)%alpha_rho(1)": 1000 * 1e-8,
    "patch_icpp(2)%alpha(1)": 1e-8,
    "patch_icpp(2)%alpha_rho(2)": 1000 * (1.0 - 1e-8),
    "patch_icpp(2)%alpha(2)": 1.0 - 1e-8,
    # "patch_icpp(2)%smoothen": "T",
    # "patch_icpp(2)%smooth_patch_id": 1,
    # "patch_icpp(2)%smooth_coeff": 4.0e00,
    # Acoustic source
    "acoustic_source": "T",
    "num_source": 1,
    "acoustic(1)%support": 5,
    "acoustic(1)%loc(1)": 0.1,
    "acoustic(1)%loc(2)": 0.5,
    "acoustic(1)%pulse": 2,
    "acoustic(1)%npulse": 1,
    "acoustic(1)%dir": 1.0,
    "acoustic(1)%mag": 1.0,
    "acoustic(1)%foc_length": 0.4,
    "acoustic(1)%aperture": 0.75,
    "acoustic(1)%gauss_sigma_time": 4e-5,
    "acoustic(1)%delay": 2e-4,
    # Fluids Physical Parameters
    "fluid_pp(1)%gamma": 1.0e00 / (4.4e00 - 1.0e00),
    "fluid_pp(1)%pi_inf": 4.4e00 * 5.57e08 / (4.4e00 - 1.0e00),
    "fluid_pp(1)%G": 0.0,
    "fluid_pp(2)%gamma": 1.0e00 / (4.4e00 - 1.0e00),
    "fluid_pp(2)%pi_inf": 4.4e00 * 5.57e08 / (4.4e00 - 1.0e00),
    "fluid_pp(2)%G": 1e9,
}

print(json.dumps(config, indent=4))
